### ISSUE TITLE
Upgrade context-propagation to 1.0.0 and micrometer-bom 1.10.0 for 1.0.0

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/tracing#116]
Update `dependencies.gradle`
And update the lock files:
```bash
./gradlew resolveAndLockAll --no-build-cache --update-locks 'io.micrometer:*'
```

**Comment by shakuzen** [comment]
I also removed the snapshot/milestone repositories so that artifacts will only be resolved from central.
