### ISSUE TITLE
Missing TraceableExecutorService class

### ISSUE THREAD

**Issue by estigma88** [micrometer-metrics/tracing#120]
Spring Boot Sleuth has a [TraceableExecutorService](https://www.javadoc.io/static/org.springframework.cloud/spring-cloud-sleuth-core/2.2.1.RELEASE/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.html) class which helps us to trace executions for async tasks inside an ExecutorService, is that class implemented somewhere in the new tracing library?

**Comment by marcingrzejszczak** [comment]
It's moved to use of Context Propagation library. You can read more about that here https://micrometer.io/docs/observation#instrumentation_of_thread_switching_components and here https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#async-instrumentation
