### ISSUE TITLE
[BUG] Loosing getter spanKind

### ISSUE THREAD

**Issue by bademux** [micrometer-metrics/tracing#123]
By creating anonymous lambda we effectively lost `RemoteGetter` type for the getter.
It means there is no way to distinct span kind (brave.propagation.Propagation.RemoteGetter#spanKind) inside custom Propagator

io.micrometer.tracing.handler.PropagatingReceiverTracingObservationHandler#onStart
```java
        Span.Builder extractedSpan = this.propagator.extract(context.getCarrier(),
                (carrier, key) -> context.getGetter().get(carrier, key));
```

**Comment by bademux** [comment]
"why do you need a span kind in a propagator?"
Good question. Due to unfotunate circumstances of biological nature I have to support custom spanId and traceId and it was done with custom Propagator. What more I need to use it only with server/client kind, as "biological nature" fails to design something that fit JMS (producer/consumer).

"As a workaround can you pass it to your carrier maybe?"
Could you please elaborate on that?

**Comment by marcingrzejszczak** [comment]
I understand that you have a custom instrumentation? Or do you want to have this info for any existing instrumentation?

**Comment by bademux** [comment]
> I understand that you have a custom instrumentation? Or do you want to have this info for any existing instrumentation?

Big Picture.

Spring Sleuth: I used composite with B3 and custom as fallback; something like that: https://github.com/spring-cloud/spring-cloud-sleuth/issues/2188

Trying to migrate to Spring Boot 3.0:
1. Add Brave manually to Jms, Executors, httpclients
2. Write Composite `brave.propagation.Propagation` to use B3 and Custom headers (maybe this should be documented somewhere, let me know and I will create separate issue)
--- I'm here ---
3. Adapt Custom `brave.propagation.Propagation` to Spring Boot 3.0

As a part of the issue I have problem with N3 - adapting Custom `brave.propagation.Propagation` to spring boot 3.0. I can't see way to figure out spanKind (server\client vs producer\consumer)

**Comment by bademux** [comment]
@marcingrzejszczak  I perfectly understand that the API relays on `brave.propagation.Propagation.Getter`, and typecasting to `RemoteGetter` can be threaded like a hack.
If you see the place (and its doable in first place) I can propose MR.
We can arrange a call, my polish is not perfect but I hope to surprise you.

I will also understand if the issue will be resolved as won't fix.

**Comment by marcingrzejszczak** [comment]
I think this is a very custom requirement. If we find more people requiring the same change we can come back to this. 

Until then I think you can crate your own implementation of `PropagatingReceiverTracingObservationHandler`  where you can pass the kind information manually to the getter.
