### ISSUE TITLE
Problem with jakarta JMS and brave

### ISSUE THREAD

**Issue by bademux** [micrometer-metrics/tracing#124]
According to 
https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/dependency-versions.html#appendix.dependency-versions.coordinates
brave version is 5.14.1, but for JMS it uses `javax` package. It is incompatible with SpringBoot 3.0 expectation.
https://github.com/openzipkin/brave/blob/5.14.1/instrumentation/jms/src/main/java/brave/jms/JmsTracing.java#L34

**Comment by marcingrzejszczak** [comment]
Ok and what should we do about this? I guess you should file an issue in Brave do that they update the jms instrumentation. 

Or suggestion is to manually instrument the code using micrometer tracing without going to the brave instrumentation code.

**Comment by bademux** [comment]
good question,
should it be excluded fro spring boot BOM as compatible?
How to play it right?

**Comment by bademux** [comment]
at first let me sorry nagging you, I just lost in libs and don't understand who is actually responsible for making tracing just work at spring as it was in Spring 2.X.
I'm really grateful for your help. There is no hurry, I just want to check upgrade path to spring boot 3.0 and report gracefully report problems if any.
I report incompatible brave jms library  in BOM for spring-boot project,

**Comment by marcingrzejszczak** [comment]
Actually, we could think of adding support for Spring JMS with Micrometer Observation. You can create an issue in the Spring project with such an enhancement request.

**Comment by monnetchr** [comment]
> Actually, we could think of adding support for Spring JMS with Micrometer Observation. You can create an issue in the Spring project with such an enhancement request.

Was such an enhancement request created yet?

**Comment by shakuzen** [comment]
Just linking here that Brave now has a JMS instrumentation module since 5.15.0 that supports the `jakarta` namespace. See https://github.com/openzipkin/brave/issues/1352
