### ISSUE TITLE
Propagating TraceId and SpanId to @Async method

### ISSUE THREAD

**Issue by hamid646m** [micrometer-metrics/tracing#127]
There doesn't seem to be away to propagate TraceId and SpanId to Async methods. Previously, it was possible to create `LazyTraceExecutor`. Is it possible

**Comment by marcingrzejszczak** [comment]
You can do it, just check out the migration guide page https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#async-instrumentation
