### ISSUE TITLE
Documentation pages is empty

### ISSUE THREAD

**Issue by GissilyWork** [micrometer-metrics/tracing#132]
Tracing documentation pages is empty. (https://micrometer.io/docs/tracing)
![8B352270-19BC-486A-8C6E-7F8AEE479AFD](https://user-images.githubusercontent.com/24429613/208285744-eb5944f8-8102-4522-bdb1-bf4306fc95f1.png)

**Comment by marcingrzejszczak** [comment]
It is not...

![image](https://user-images.githubusercontent.com/3297437/208287083-cba0ce4c-7f2c-4285-ac6e-d963ee10231c.jpeg)

**Comment by jonatan-ivanov** [comment]
Please try to force refresh the page.
