### ISSUE TITLE
Next release date for micrometer-tracing-bridge-otel

### ISSUE THREAD

**Issue by brumarqu-te** [micrometer-metrics/tracing#136]
This is not really a bug nor an enhancement but more of an information request. When are you planning to release the fix made [here](https://github.com/micrometer-metrics/micrometer/issues/3564)?
I'm currently using `io.micrometer:micrometer-tracing-bridge-otel:1.0.1-SNAPSHOT` but need to bump the version so i can release my own services to production.

**Comment by jonatan-ivanov** [comment]
We usually had patch releases monthly (December was an exception) around the mid-month, a few days before Spring Boot releases.
Now that Spring Framework 6.x also depends on Micrometer (not on tracing though), we might need to bring the release date closer to the beginning of a month, see: https://calendar.spring.io/

Let me discuss this with @shakuzen and @marcingrzejszczak, we might do a release on Monday (2023-01-09).
