### ISSUE TITLE
Does micrometer-tracing support opentelemetry-exporter-otlp

### ISSUE THREAD

**Issue by chaitanya87** [micrometer-metrics/tracing#147]
Can I use opentelemetry-exporter-otlp to export span using OTLP via  gRPC.

`<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-otel</artifactId>
			<version>1.0.1</version>
		</dependency>`
`<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-otlp</artifactId>
			<version>1.19.0</version>
		</dependency>`

P.S. As per https://micrometer.io/docs/tracing#_supported_reporters, I am able to use opentelemetry-exporter-zipkin in my Spring Boot 3.0.1 application.

**Comment by marcingrzejszczak** [comment]
Not out of the box, but you can add the dependency and create the `SpanExporter` bean (https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/OpenTelemetryAutoConfiguration.java#L118-L121) like the one shown here (https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpSpanExporterProvider.java). Boot will autoconfigure that into the OTel Tracer.
