### ISSUE TITLE
Ability to exclude some endpoints from being traced

### ISSUE THREAD

**Issue by fatihdogmus** [micrometer-metrics/tracing#148]
Hello,

I've basically scoured the internet and the source codes, but couldn't find a way to exclude some URL patterns from being traced.

We use Otel bridge and zipkin exporter to get the trace data. Our use case is that there are a lot of traces regarding actuator, for both health and prometheus endpoints.

My question is that is there a way to exclude some URLs trace data being pushed to zipkin?

Thank you.

**Comment by fatihdogmus** [comment]
Yeah we are using spring boot. I will open an issue there. But meanwhile, I think I found a (hacky) workaround.

Since our sole use case is for the actuator endpoints, which don't send any HTTP requests, I created my own `CompositeSpanExporter` and overriden the `export` function like that:
```java
public class FilteredZipkinExporter extends CompositeSpanExporter {

    public FilteredZipkinExporter(ZipkinSpanExporter zipkinSpanExporter) {
        super(List.of(zipkinSpanExporter), null, null, null);
    }

    @Override
    public CompletableResultCode export(Collection<SpanData> spans) {
        Set<String> actuatorTraceIds = spans.stream()
                .filter(span -> span.getName().contains("actuator"))
                .map(SpanData::getTraceId)
                .collect(toSet());

        List<SpanData> nonActuatorSpans = spans.stream()
                .filter(span -> !actuatorTraceIds.contains(span.getTraceId()))
                .collect(toList());

        return super.export(nonActuatorSpans);
    }
}
```

I take `ZipkinSpanExporter` that spring boot creates, so that I don't need to do any publishing myself. Then find the trace IDs of spans that have the name "actuator" in them, since Micro meter publishes the span name to include the actual URL, then I filter out all the spans that have this trace ID.

But this is not enough. Since `ZipkinSpanExporter` is also registered as bean, I need to replace the bean with a `BeanPostProcessor` otherwise two span exporter beans are present so both of them are called.
```java
@Configuration
public class ZipkinSpanExporterPostProcessor implements BeanPostProcessor {

    @Override
    public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
        if(bean instanceof ZipkinSpanExporter zipkinSpanExporter) {
            return new FilteredZipkinExporter(zipkinSpanExporter);
        }
        return bean;
    }
}

```

Then only my `FilteredZipkinExporter` is present as a `SpanExporter`

I know this is hacky but I tried your solution, but that gets the spans one by one, so I can filter out the spans that are actually related to actuator, but all the other spans that are related with this trace gets pushed to zipkin.

**Comment by jonatan-ivanov** [comment]
Since you are using Boot, the instrumentation there is using the Observation API.
So by creating an `ObservationPredicate` `@Bean` you can exclude what you don't want. Here is an example with Spring MVC and Spring Cloud OpenFeign for incoming and outgoing HTTP requests for actuator endpoints:

https://github.com/jonatan-ivanov/teahouse/blob/37e537b276b522f301b987dd88ad621b7a27ff9d/core/src/main/java/org/example/teahouse/core/actuator/config/CommonActuatorConfig.java#L24-L46

**Comment by jonatan-ivanov** [comment]
As far as I can tell, the details here should answer your question, let me close the issue.
Please feel free to let us know if you want it to be reopened.
