### ISSUE TITLE
Spring Webclient Header Propagation

### ISSUE THREAD

**Issue by cantaylancapraz** [micrometer-metrics/tracing#149]
Hi,

Until this time, I was using spring cloud sleuth for propagation. I was using b3 propagation. However, after upgrading to spring 3.0 I removed sleuth, switched to micrometer tracing. I started not being able to [propagate b3](https://github.com/openzipkin/b3-propagation) headers.

I am using Spring 3.0 + Webflux + Webclient.

To be more specific, my request is:
When I call an endpoint that calls the external source via WebClient, headers such as X-B3-SpanId should be added if there is not, and propagate if there exists.

I did a lot of research, tried many ways, but couldn't solve my problem. I couldn't find any documentation or sample project that provides how to do it. Nothing I've tried has worked either. 

I need the guidance of community.

Best regards

**Comment by marcingrzejszczak** [comment]
Please check this sample for reference https://github.com/micrometer-metrics/micrometer-samples/tree/main/webflux

**Comment by cantaylancapraz** [comment]
Thanks 

I've actually seen this. But I believe it is very inefficient to apply this to many points in the code. 
Maybe we can think about how we can make this work more practical.

**Comment by jonatan-ivanov** [comment]
I think I might miss something but your issue is that B3 headers are not propagated when you receive a request with webflux and in the controller you want to send another with webclient?
Do you see the W3C header being propagated (`traceparent`)?

**Comment by cantaylancapraz** [comment]
No, W3C headers are not propagated as well.

**Comment by cantaylancapraz** [comment]
Yes.

When I don't set **management.tracing.propagation.type as B3**, traceparent header is propagated.

**Comment by cantaylancapraz** [comment]
By the way, now I now able to pass a single b3 header. I will create a sample project and share it here.

However, following headers are still not propagated. 
x-b3-parentspanid, x-b3-sampled, x-b3-spanid, x-b3-traceid

**Comment by jneate** [comment]
@cantaylancapraz is a `B3` header being propagated?

The issue we have is that after the upgrade it's defaulting to a single B3 header instead of the multiple X-B3 headers.
If we supply our own Propagation.Factory via

```java
@Bean
Propagation.Factory get() {
    return B3Propagation.newFactoryBuilder().injectFormat(B3Propagation.Format.MULTI).build();
}
```

we gain the X-B3 multi headers but lose the propagation of remote baggage headers so that might fix your issue but it raises another one for us.

(Related remote baggage fix https://github.com/micrometer-metrics/micrometer/issues/3564)

**Comment by marcingrzejszczak** [comment]
You're close @jneate , just create your beans like this

```java
@Bean
		BaggagePropagation.FactoryBuilder myPropagationFactoryBuilder(
				ObjectProvider<BaggagePropagationCustomizer> baggagePropagationCustomizers) {
			Factory delegate = B3Propagation.newFactoryBuilder().injectFormat(B3Propagation.Format.MULTI).build();
			FactoryBuilder builder = BaggagePropagation.newFactoryBuilder(delegate);
			baggagePropagationCustomizers.orderedStream().forEach((customizer) -> customizer.customize(builder));
			return builder;
		}
```

**Comment by artemptushkin** [comment]
@marcingrzejszczak Hi, I bumped into [this issue](https://github.com/micrometer-metrics/tracing/issues/149#issuecomment-1403545652)

> it's defaulting to a single B3 header instead of the multiple X-B3 headers

I wonder why is it _single_ `b3` now and not _multi_? Is it documented somewhere? (I can not find) It's actually a breaking change that we could bypass, imo

**Comment by artemptushkin** [comment]
@shakuzen this is different that you post, I'm asking about _multi_ header approach

We had 3 headers with sb 2.7, e.g. `x-b3-traceid` and others
but now by default, it's just one header: `b3`

Please see this code https://github.com/spring-projects/spring-boot/blob/157b71b333473c2633b17362df1be83d6f9eaaed/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/BraveAutoConfiguration.java#L183

**Comment by shakuzen** [comment]
My apologies that things weren't reflected on the issue I linked or the pull request linked from there at the time I made my comment (I also didn't explicitly mention the linked pull request). We had already discussed internally about the requests here and elsewhere for b3 multi header support, and it was subsequently added to the pull request. Please see https://github.com/spring-projects/spring-boot/pull/35611. That will add support for configuring b3 multi via properties.
