### ISSUE TITLE
Cannot dynamically add baggage to micrometer otel instrumentation

### ISSUE THREAD

**Issue by adamleantech** [micrometer-metrics/tracing#159]
FYI I originally asked about this on [stackoverflow](https://stackoverflow.com/questions/75232257/cannot-dynamically-add-baggage-to-micrometer-otel-instrumentation-spring-boot) but did not receive any response.

I have a Spring Boot 3.0.2 app that is written with reactive components configured with micrometer otel bridge for tracing.  This pulls in the io.micrometer:micrometer-tracing:1.0.1 dependency transitively.

```
    <dependencyManagement>
        <dependencies>
            <!-- Import dependency management from Spring Boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.0.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
...
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core-micrometer</artifactId>
        </dependency>
```

What I would like to do is dynamically add baggage while processing REST requests to be propagated to downstream services.

I cannot see a way of achieving this as the TracingObservationHandler.TracingContext class holds the baggage context that is propagated through PropagatingSenderTracingObservationHandler and the class is package private, hence it is not possible to add additional baggage within my application code.

I believe this could be resolved if the TracingObservationHandler.TracingContext was public by using something like the following.

```
        Observation obs = context.get(ObservationThreadLocalAccessor.KEY);
        TracingContext ctxt = obs.getContext().get(TracingObservationHandler.TracingContext.class);
        tracer.createBaggage(key).set(ctxt.getSpan().context(), value);
```

Perhaps there is an alternative way of adding baggage that i am not aware of?

**Comment by marcingrzejszczak** [comment]
You can't add it dynamically. Baggage needs to be known upfront.

**Comment by adamleantech** [comment]
Can I ask why that is the case?  The w3 standard clearly allows for baggage to be mutated including adding new key/value pairs
https://www.w3.org/TR/baggage/#mutating-baggage

**Comment by marcingrzejszczak** [comment]
Actually, I double-checked the code and the baggage propagation that I mentioned needs to be known upfront only in the case of being backward compatible with Sleuth / B3 based baggage propagation where the name of the baggage field = a header key.  Otherwise it should just work with the baggage API and then it will be put in to the `baggage` field according to the spec. Do you have a sample that shows that it's not possible to achieve this?

**Comment by marcingrzejszczak** [comment]
Can you prepare a Maven & Java sample that replicates this? It would be much easier to try to help you out...

BTW `TracingObservationHandler.TracingContext` is not package private, it's part of the public interface.

**Comment by adamleantech** [comment]
you're absolutely right, my mistake.  I think i've figured out how to do this, many thanks
