### ISSUE TITLE
MDC includes field "micrometer.observation" instead of "traceId" and "spanId" (WebFlux, OTel)

### ISSUE THREAD

**Issue by janekbettinger** [micrometer-metrics/tracing#161]
### Current Behavior

In a Spring WebFlux application we observe that the MDC includes the field `micrometer.observation` and misses the fields `traceId` and `spanId`. 

### Expected Behavior

MDC should include `traceId` and `spanId` but not the deserialized tracing context `micrometer.observation`.

### Additional Information

* micrometer-tracing 1.0.0
* micrometer-tracing-bridge-otel 1.0.0
* spring-boot-starter-webflux
* Spring Boot 3.0.2
* Spring Cloud 2022.0.0

In the debugger I've observed that the MDC is properly filled with the trace and span ID in `io.micrometer.tracing.otel.bridge.Slf4JEventListener`, but the MDC seems to be cleared in the same class before the log message is actually produced (`LOGGER.info("Hello Micrometer")`). Unfortunately, I haven't found the location where `micrometer.observation` is put into the MDC.

_Sample log message_ (see huge `micrometer.observation` field that includes trace and span IDs):
```json
{
   "http_method":"GET",
   "micrometer.observation":"{name=http.server.requests(null), error=null, context=name='http.server.requests', contextualName='null', error='null', lowCardinalityKeyValues=[exception='none', method='GET', outcome='SUCCESS', status='200', uri='UNKNOWN'], highCardinalityKeyValues=[http.url='/appname'], map=[class io.micrometer.core.instrument.Timer$Sample='io.micrometer.core.instrument.Timer$Sample@31a265a1', class io.micrometer.tracing.handler.TracingObservationHandler$TracingContext='TracingContext{span=PropagatedSpan{ImmutableSpanContext{traceId=cccc57138124e9ad98471b63ac35f5b4, spanId=a21ea5ea0ac311fb, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}}, scope=null}', class io.micrometer.core.instrument.LongTaskTimer$Sample='SampleImpl{duration(seconds)=15.019349547, duration(nanos)=1.5019349547E10, startTimeNanos=116363259614882}'], parentObservation=null}",
   "interface org.springframework.security.core.context.SecurityContext":"MonoLiftFuseable",
   "interface org.springframework.web.server.ServerWebExchange":"org.springframework.web.server.adapter.DefaultServerWebExchange@380078e5",
   "http_url":"/foo",
   "log_level":"INFO",
   "log_message":"Hello Micrometer",
   "class":"x.x.x.x.x.SampleEndpoint"
}
```

_logback-spring.yml_ (simplified for this example; see `<mdc/>` tag):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="json" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <mdc/>
                <pattern>
                    <omitEmptyFields>true</omitEmptyFields>
                    <pattern>
                        {
                            "log_level": "%level",
                            "log_message": "%message",
                            "class": "%logger{40}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>
    <root level="INFO">
        <appender-ref ref="json" />
    </root>
</configuration>
```

**Comment by janekbettinger** [comment]
Little update: I've just seen the comment https://github.com/spring-projects/spring-boot/issues/33372#issuecomment-1431142013 and tried the latest releases introducing `Hooks.enableAutomaticContextPropagation()`.

For log statements within a `org.springframework.web.server.WebFilter` the `traceId` and `spanId` are now automatically written into the MDC.

For other log statements (like in my initial post), there's still the need for wrapping them to get the `traceId` and `spanId`:
```java
return Mono.deferContextual(contextView -> {
      try (ContextSnapshot.Scope ignored = ContextSnapshot.setThreadLocalsFrom(contextView, ObservationThreadLocalAccessor.KEY)) {
        LOGGER.info("Hello Micrometer");
        return getMyFlux();
      }});
```
The whole point why I've created this issue in first place is that I wonder why the automated injection of `micrometer.observation` works, whereas for `traceId` and `spanId` we still need the said boilerplate code. Maybe it's possible to apply the injection approach used for the former for the tracing IDs as well?

**Comment by marcingrzejszczak** [comment]
There should be no need to do so. Without a sample it will be difficult to help you.

**Comment by marcingrzejszczak** [comment]
You also have additional entries in the MDC such as interfaces etc. I don't think it has anything to do with micrometer tracing

**Comment by marcingrzejszczak** [comment]
Ping @janekbettinger ?

**Comment by janekbettinger** [comment]
Hi, unfortunately I have no time at the moment to dig deeper into this (e.g. breakpoint in `MDC.put` did not reveal "who" writes `micrometer.observation` into the MDC as it was not called for said field). As you wrote that Micrometer Tracing itself does not put it into the MDC I'm closing this issue. Thanks for the feedback!
