### ISSUE TITLE
Does micrometer-tracing support tracing of rabbitMQ messages?

### ISSUE THREAD

**Issue by bystrzano4** [micrometer-metrics/tracing#162]
Hey,
I'm migrating from Sleuth to Micrometer according to https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide.
Currently, I'm testing tracing in scope of communication with RabbitMQ.
However, traceId and spanId in RabbitMQ messages seem to not be working for me - both traceId and spanId are null, as is the TraceContext in the _io.micrometer.tracing.Tracer_, that I inject.
I've got the latest Spring-boot with the Spring AMQP and the _micrometer-tracing-bridge-brave_ dependency.

REST calls are working fine - traceId is there.

Is that a known issue or am I missing something?

**Comment by marcingrzejszczak** [comment]
We do support it via Spring Amqp. We will be working on native support of RabbitMQ - you can check the issue here https://github.com/rabbitmq/rabbitmq-java-client/issues/952  .

**Comment by marcingrzejszczak** [comment]
Here you have an example of how to work with just Rabbitmq code - https://github.com/micrometer-metrics/micrometer-samples/pull/25
