### ISSUE TITLE
Feature parity with sleuth's annotations

### ISSUE THREAD

**Issue by dimi-nk** [micrometer-metrics/tracing#163]
Sleuth supported some annotations to declaratively extract tracing tags, e.g. `@SpanTag`, see [sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/tree/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/annotation). These annotations exist in micrometer tracing but are not yet implemented, according to @marcingrzejszczak. Could we please hook them up? :)

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/micrometer-metrics/tracing/commit/ca3241d8fdca61a295af998143b4c3d9eb144c07

**Comment by dimi-nk** [comment]
Amazing @marcingrzejszczak. Thanks for the quick resolution.
