### ISSUE TITLE
Does micrometer-tracing able to generate custom traceId 

### ISSUE THREAD

**Issue by mukkul-rk** [micrometer-metrics/tracing#169]
Currently I'm getting the trace ID in some format as 63ea6bd0e1cb5cad447259e82b040a14, is there any way in which we can customize this ID's or is there any way by which I can update this trace ID with a value received from API call header.

**Comment by marcingrzejszczak** [comment]
Maybe you could theoretically create your own custom identifiers but you would need to customize Brave and OTel to achieve that and I'm not sure that that would actually work in the long run. So micrometer-tracing as such doesn't support that.
