### ISSUE TITLE
No traces in Async or Scheduler

### ISSUE THREAD

**Issue by skshyamal** [micrometer-metrics/tracing#178]
According to the Async Instrumentation in migration [guide](https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide) does not work at all, or am I doing something wrong.

**Comment by skshyamal** [comment]
After configuring AsyncConfigure like `@Configuration
@ConditionalOnEnabledTracing
@RequiredArgsConstructor
public class TraceAsyncConfiguration implements AsyncConfigurer {

    private final TaskExecutorBuilder taskExecutorBuilder;

    @Override
    public Executor getAsyncExecutor() {
        return ContextExecutorService.wrap(threadPoolTaskExecutor().getThreadPoolExecutor(), ContextSnapshot::captureAll);
    }

    @Bean
    public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
        return taskExecutorBuilder.build();
    }

}@Configuration
@ConditionalOnEnabledTracing
@RequiredArgsConstructor
public class TraceAsyncConfiguration implements AsyncConfigurer {

    private final TaskExecutorBuilder taskExecutorBuilder;

    @Override
    public Executor getAsyncExecutor() {
        return ContextExecutorService.wrap(threadPoolTaskExecutor().getThreadPoolExecutor(), ContextSnapshot::captureAll);
    }

    @Bean
    public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
        return taskExecutorBuilder.build();
    }

}@Configuration
@ConditionalOnEnabledTracing
@RequiredArgsConstructor
public class TraceAsyncConfiguration implements AsyncConfigurer {

    private final TaskExecutorBuilder taskExecutorBuilder;

    @Override
    public Executor getAsyncExecutor() {
        return ContextExecutorService.wrap(threadPoolTaskExecutor().getThreadPoolExecutor(), ContextSnapshot::captureAll);
    }

    @Bean
    public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
        return taskExecutorBuilder.build();
    }

}@Configuration
@ConditionalOnEnabledTracing
@RequiredArgsConstructor
public class TraceAsyncConfiguration implements AsyncConfigurer {

    private final TaskExecutorBuilder taskExecutorBuilder;

    @Override
    public Executor getAsyncExecutor() {
        return ContextExecutorService.wrap(threadPoolTaskExecutor().getThreadPoolExecutor(), ContextSnapshot::captureAll);
    }

    @Bean
    public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
        return taskExecutorBuilder.build();
    }

}`

worked atleast with the Async but no luck with Scheduler.

* One very annoying thing have been observed in case SpringBottTest with @AutoConfigureObservability everything works fine without any extrac configuration

The question is that is there any special context propagation happens in Spring boot test context??

**Comment by marcingrzejszczak** [comment]
`@Scheduled` is not supported at this point - https://github.com/spring-projects/spring-framework/issues/29883
