### ISSUE TITLE
JMS coralationId autoconfigure

### ISSUE THREAD

**Issue by fr3sh** [micrometer-metrics/tracing#219]
Due the migration of sluth to micrometer, where can I find a parameter to automatically set the
traceId and spanId to the JMS message.
Previously, this was the configuration metter:

spring.sleuth.messaging.jms.enabled

Do I need to configure of exectutors for that? Can you give me a hint?

**Comment by k-dabrowska-kubik** [comment]
I have the same problem with Spring Boot 3.0.5.
Tracing in microservice where flow is starting from JMS (Artemis) doesn't work.
I will be grateful for any help.

**Comment by marcingrzejszczak** [comment]
We don't have instrumentations in tracing (except for kotlin really). I guess this should be done either in Micrometer for JMS native support or in Spring JMS for Spring based support.

**Comment by simasch** [comment]
I have the same issue. Before with Sleuth, everything worked out of the box with JMS.
Also, with Spring Boot 3.1.0 this is not working.

**Comment by mbadziong** [comment]
Spring Boot 3.1.1 still not working. Folks, have you any workaround for this?

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-projects/spring-framework/issues/30335

**Comment by bclozel** [comment]
The Jakarta JMS instrumentation is being contributed under https://github.com/micrometer-metrics/micrometer/pull/4007; please review the observations and their KeyValues to check that they fit your use cases.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/micrometer-metrics/micrometer/pull/4007
