### ISSUE TITLE
Quartz and ex-Sleuth

### ISSUE THREAD

**Issue by amitvocate** [micrometer-metrics/tracing#222]
I would like to report a bug/feature request related to the integration of micrometer and quartz.
Previously (in sleuth), each job execution had a span ID, but it seems that this feature was not carried over to micrometer-tracing. I was wondering if this will be ported over in the future.

I attempted to create a span using the following code:

`var span = tracer.nextSpan().start();
log.info("AmitDemoJob");
span.end();`

However, I was unable to see any span ID.
I am using the Brave integration in Spring Boot, and when debugging the BraveSpan, I noticed that the delegate is set to "NoopSpan" (if this is of any help)

I would greatly appreciate any assistance in resolving this issue.

Thank you.

**Comment by marcingrzejszczak** [comment]
> var span = tracer.nextSpan().start(); log.info("AmitDemoJob"); span.end();

you need to put the span in scope + modify your logging pattern to see things in the logs.

```yml
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
```

and the code

```java
var span = tracer.nextSpan().start(); 
try (Tracer.SpanInScope scope = tracer.withSpan(span)) {
  log.info("AmitDemoJob");       
}
span.end();
```

**Comment by amitvocate** [comment]
Thanks so much.
I was not aware i needed a scope.

**Comment by amitvocate** [comment]
Regarding my other question - will the quartz integration that was in sleuth be ported in the future?
