### ISSUE TITLE
otel-bridge: add trace_flags to MDC

### ISSUE THREAD

**Issue by olivierboudet** [micrometer-metrics/tracing#229]
In `Slf4JEventListener`of `micrometer-tracing-otel-bridge`, `span_id` and `trace_id` are added to MDC.
https://github.com/micrometer-metrics/tracing/blob/4f14a45025d6352cfa84a0c41435f6f105c8acbe/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/Slf4JEventListener.java#L58
Would it be possible to add also `trace_flags` which allow to know when a request is sampled (see https://www.w3.org/TR/trace-context/#trace-flags)

**Comment by olivierboudet** [comment]
I would like to log the `traceFlags` field. I am currently using the opentelemetry java agent and have a log pattern like this : 
`%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %X{correlation-id:--} %X{trace_id:--} %X{trace_flags:--} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:0}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}`
I am just trying to have a similar behavior with micrometer tracing (with Spring Boot).

**Comment by marcingrzejszczak** [comment]
There's no point in having this in the logs out of the box. If we're talking about log correlation it doesn't matter if the span is sampled or not.

**Comment by olivierboudet** [comment]
If it does not make sense to have it out of the box, can you explain a bit how can I have it with custom code please ?

I though to write a custom `EventListener` to insert `traceFlags` information in MDC put all methods of `Scope*Event` are protected.
I am trying to do something like that : 
```
package com.cooperl.csuite.pass.eleveur.common;

import io.micrometer.tracing.otel.bridge.EventListener;
import io.micrometer.tracing.otel.bridge.EventPublishingContextWrapper;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;

@Component
public class SLF4JEventListener implements EventListener {

    public static final String TRACE_FLAGS = "trace_flags";

    @Override
    public void onEvent(Object event) {
        if (event instanceof EventPublishingContextWrapper.ScopeAttachedEvent) {
            onScopeAttached((EventPublishingContextWrapper.ScopeAttachedEvent) event);
        }
        else if (event instanceof EventPublishingContextWrapper.ScopeClosedEvent) {
            onScopeClosed();
        }
        else if (event instanceof EventPublishingContextWrapper.ScopeRestoredEvent) {
            onScopeRestored((EventPublishingContextWrapper.ScopeRestoredEvent) event);
        }
    }

    private void onScopeClosed() {
        MDC.remove(TRACE_FLAGS);
    }

    private void onScopeAttached(EventPublishingContextWrapper.ScopeAttachedEvent event) {
        MDC.put(TRACE_FLAGS, event.getSpan().getSpanContext().getTraceFlags()); // does not work, getSpan() is not public

    }

    private void onScopeRestored(EventPublishingContextWrapper.ScopeRestoredEvent event) {
        MDC.put(TRACE_FLAGS, event.getSpan().getSpanContext().getTraceFlags()); // does not work, getSpan() is not public
    }
}

```

**Comment by marcingrzejszczak** [comment]
I've opened the scope of getters for tracing `1.1.0`. Until then you need to either use reflection or create a class in the `io.micrometer.tracing.otel.bridge` that will be able to access the package scope methods.

**Comment by olivierboudet** [comment]
Thanks a lot !
