### ISSUE TITLE
JavaDoc : Propagator references Open Telemetry classes which is not part of Micrometer

### ISSUE THREAD

**Issue by jjoslet** [micrometer-metrics/tracing#230]
The JavaDoc in the [`Propagator`](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing/src/main/java/io/micrometer/tracing/propagation/Propagator.java) class references `TextMapPropagator` from Open Telemetry which is not part of Micrometer.

This is present at line [96](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing/src/main/java/io/micrometer/tracing/propagation/Propagator.java#L96) and [133](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing/src/main/java/io/micrometer/tracing/propagation/Propagator.java#L133)

**Comment by shakuzen** [comment]
Closed by #236
