### ISSUE TITLE
Support numeric attributes value for tracing attributes

### ISSUE THREAD

**Issue by nikoncode** [micrometer-metrics/tracing#234]
Current convention support only string valued attributes for observation (future span), but modern tracing backend support numbers in it, which might significantly simplify filtering.

For example, http.status_code (as number) might be used in filter like http.status_code > 200 and http.status_code < 300, but in case of string it's not quite possible.

**Comment by nikoncode** [comment]
Same thing for boolean types.

**Comment by nikoncode** [comment]
@marcingrzejszczak are you ok if I contribute to make this available at least on span level?

**Comment by marcingrzejszczak** [comment]
Yes, I commented on the PR

**Comment by marcingrzejszczak** [comment]
done via https://github.com/micrometer-metrics/tracing/commit/13f060c3448b4e0bf7adb00fbd19621f3d58d0e0
