### ISSUE TITLE
Add support for customizing a span before the span ends

### ISSUE THREAD

**Issue by twicksell** [micrometer-metrics/tracing#247]
To support collecting tags like thread name and id, please consider adding some component that allows for customizing a span before the span ends or is otherwise invoked in the instrumenting thread. `SpanFilter` is invoked on the exporter thread, and as such cannot be used in this case. 

Alternatively, Micrometer could support adding thread name and id by default (configurable via a property). See [OTel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-thread-attributes) for suggesting naming conventions.

**Comment by marcingrzejszczak** [comment]
Are you using this through Micrometer Observation? In that case you could create an `ObservationFilter` that would be called before a span is getting closed. Or are you using Micrometer Tracing API directly?

**Comment by marcingrzejszczak** [comment]
Closing due to lack of feedback
