### ISSUE TITLE
Instrument tracing information for every execution of the scheduled method

### ISSUE THREAD

**Issue by sondemar** [micrometer-metrics/tracing#254]
After the replacement of Spring Cloud Sleuth integration with Micrometer integration with a new version of Spring Boot 3.x we lost tracing information creation for the method annotated with [Scheduled annotation](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/Scheduled.html) which was available out of the box with mentioned [Sleuth integration](https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/integrations.html#sleuth-async-scheduled-integration).

Without this functionality, every developer needs to implement their own support, so is there a chance to reflect Sleuth functionality inside the Micrometer implementation?

Please let me know if you need a contribution to the implementation.

**Comment by jonatan-ivanov** [comment]
This should be implemented in Spring Framework, see: https://github.com/spring-projects/spring-framework/issues/29883

Users do not need to implement their own support, they can use `@Observed` as a workaround, see: https://github.com/spring-projects/spring-framework/issues/29883#issuecomment-1454325369
