### ISSUE TITLE
Dependency on micrometer-bom RC1 version in GA release

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/tracing#255]
Tracing 1.1.0 was released with a dependency on micrometer-bom 1.11.0-RC1, which should not have happened for the GA release. We should upgrade to micrometer-bom 1.11.0 and remove any non-GA versions.

**Comment by jonatan-ivanov** [comment]
Fixed in https://github.com/micrometer-metrics/tracing/commit/362fabd8a353942e305ef7f5bd9e23ab1f58cfaf
