### ISSUE TITLE
http-nio thread stuck with same trace ID across requests

### ISSUE THREAD

**Issue by navaneeth-spotnana** [micrometer-metrics/tracing#257]
We are migrating our web servcies from Springboot 2.7 to 3.0.6.

After running fine for a few hours, it is observed that a request processing thread (http-nio-8080-exec-9) is using the same trace ID across all requests that it's processing. Also, baggage that is set from the old request is not cleared.

After a few hours, a second thread also showed the same behaviour. We are using Sringboot 3.0.6 / micrometer 1.10.7 / tracing 1.0.4.

Each logline corresponds to a fresh web request:
![image](https://github.com/micrometer-metrics/tracing/assets/57885431/d2766b3b-542a-48d6-ab84-9d8a02de1d25)

**Comment by debraj-manna** [comment]
The issue has been discussed in [observability](https://micrometer-metrics.slack.com/archives/C030GTHE4P6/p1682020012934739) slack channel

**Comment by navaneeth-spotnana** [comment]
Workaround for now is to always reset the trace at the start of every request by defining a `OncePerRequestFilter`:

```
/**
 * Clear trace context if it's present. This is heavy hammered approach to clear trace context till
 * this issue is resolved: https://github.com/micrometer-metrics/tracing/issues/257
 */
@Component
// has to run before org.springframework.web.filter.ServerHttpObservationFilter
@Order(Ordered.HIGHEST_PRECEDENCE)
@RequiredArgsConstructor
public class ResetTraceContextFilter extends OncePerRequestFilter {
  private final CurrentTraceContext currentTraceContext;

  @Override
  protected void doFilterInternal(
      final HttpServletRequest request,
      final HttpServletResponse response,
      final FilterChain filterChain)
      throws ServletException, IOException {
    currentTraceContext.maybeScope(null);

    filterChain.doFilter(request, response);
  }
}

```

**Comment by marcingrzejszczak** [comment]
Is this still a problem? We've done a lot of changes to our scoping mechanisms since this got filed - things should work much better now.

**Comment by navaneeth-spotnana** [comment]
@marcingrzejszczak Which version onwards are these changes done? We can upgrade to that version, test and let you know?

**Comment by marcingrzejszczak** [comment]
All latest tracing and micrometer and context propagation ga versions in all branches. So just upgrade to the latest patch version.

**Comment by marcingrzejszczak** [comment]
Closing due to lack of feedback
