### ISSUE TITLE
micrometer-tracing-bridge-otel is not setting span name in extract() resulting Jaeger remote sampler perOperation to fail

### ISSUE THREAD

**Issue by jtorkkel** [micrometer-metrics/tracing#259]
**Current behavior:**

OpenTelemetry Jaeger [Java remote sampler client Library](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/jaeger-remote-sampler)  use the spanName as hashMap [key](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/PerOperationSampler.java#L45) to match perOperationSampler 
against configuration exposed through Jaeger Remote Sampler [operation_strategies/operation](https://www.jaegertracing.io/docs/1.45/sampling/#remote-sampling). Matching is exact match due usage of hashmap.

[OtelPropagator.class Span.Builder extract(C carrier, final Propagator.Getter<C> getter)](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelPropagator.java#L78) currently pass empty string "" to [SDKSpanBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java#L55) which use it as spanName.
```
return OtelSpanBuilder.fromOtel(this.tracer.spanBuilder("")).setParent(otelTraceContext);
```

Span name is empty and set to [FALLBACK_SPAN_NAME]
```
final class SdkTracer implements Tracer {
  static final String FALLBACK_SPAN_NAME = "<unspecified span name>";
}
```

This result that first spanName "unspecified span name" in http server span does not match to any operation and fall back to per service sampling configuration. spanName matching operation entry for http server should be  in format **http method path** like **http get foo/detail** 

Currently micrometer observation set spanName to [return "http %s %s".formatted(httpMethod, context.getPathPattern());](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/server/reactive/observation/DefaultServerRequestObservationConvention.java#L87) only in [stop()](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java#L185)  which is too late for operation based sampling which require span to be set prior sampling.

**Expected behavior:**
extract should set use real span name for http server for example:
- in same format as in stop/getContextualName like **http method path** like **http get foo/detail**
- without http prefix
- Allow hooks to customize the spanName.

Seems that each framework use "custom format", but very few if none allow customization.  My own preference would be simple **method path** like **get foo/detail**). But most important is the pass the meaningful spanName created by observation.

Available span name can be generated from carrier.request
carrier.request.method + '  ' +  carrier.request.path

All subSpan should either reuse the same Span name and custoize real spanName later. Or use parent span sampling decission.

Setup:
SpringBoot 3.0.5
Jaeger remote sampler 1.19.0
Micrometer tracing bridge otel 1.0.3
Java 17

Enable SB3 tracing with otel tracer, otel zipkin exporter and jaeger remote sampler
 ```
       <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-zipkin</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk-extension-jaeger-remote-sampler</artifactId>
        </dependency>
```
Configure remote sampler using Bean
```
    @Bean
    Sampler otelSampler() {
        Sampler rootSampler = JaegerRemoteSampler.builder()
                .setServiceName("foo")
                .setPollingInterval(Duration.ofSeconds(100))
                .setEndpoint("http://localhost:14251")
                .setInitialSampler(Sampler.parentBased(Sampler.traceIdRatioBased(0.001)))
                .build();
        return rootSampler;
    }
```

Use jaeger with remote sampler option enabled strategies.json like
```
{
  "service_strategies": [
    {
      "service": "foo",
      "type": "probabilistic",
      "param": 0.8,
      "operation_strategies": [
        {
          "operation": "http get /detail",
          "type": "probabilistic",
          "param": 0.2
        },
        {
          "operation": "http get /all",
          "type": "probabilistic",
          "param": 0.4
        }
      ]
    },
    {
      "service": "bar",
      "type": "ratelimiting",
      "param": 5
    }
  ],
  "default_strategy": {
    "type": "probabilistic",
    "param": 0.1,
    "operation_strategies": [
      {
        "operation": "/health",
        "type": "probabilistic",
        "param": 0.0
      },
      {
        "operation": "/metrics",
        "type": "probabilistic",
        "param": 0.0
      }
    ]
  }
}
```
extract from impacted code path, same as in links above
```
public class OtelPropagator implements Propagator {
    public <C> Span.Builder extract(C carrier, final Propagator.Getter<C> getter) {
        Context extracted = this.propagator.extract(Context.current(), carrier, new TextMapGetter<C>() {
            public Iterable<String> keys(C carrier) {
                return OtelPropagator.this.fields();
            }
            public String get(C carrier, String key) {
                return getter.get(carrier, key);
            }
        });
        io.opentelemetry.api.trace.Span span = io.opentelemetry.api.trace.Span.fromContextOrNull(extracted);
        OtelTraceContext otelTraceContext = getOtelTraceContext(extracted, span);
        return OtelSpanBuilder.fromOtel(this.tracer.spanBuilder("")).setParent(otelTraceContext); // pass "" as spanName, should pass <scheme method path"
    }
}
```

```
final class SdkTracer implements Tracer {
  static final String FALLBACK_SPAN_NAME = "<unspecified span name>";
}
```

```
final class SdkSpanBuilder implements SpanBuilder {
  SdkSpanBuilder(
      String spanName,
      InstrumentationScopeInfo instrumentationScopeInfo,
      TracerSharedState tracerSharedState,
      SpanLimits spanLimits) {
    this.spanName = spanName;
    this.instrumentationScopeInfo = instrumentationScopeInfo;
    this.tracerSharedState = tracerSharedState;
    this.spanLimits = spanLimits;
  }
}
```

```
class PerOperationSampler implements Sampler {
  @Override
  public SamplingResult shouldSample(
      Context parentContext,
      String traceId,
      String name, // passed spanName is empty and defaul to 
      SpanKind spanKind,
      Attributes attributes,
      List<LinkData> parentLinks) {
    Sampler sampler = this.perOperationSampler.get(name);
    if (sampler == null) {
      sampler = this.defaultSampler;
    }
    return sampler.shouldSample(parentContext, traceId, name, spanKind, attributes, parentLinks);
  }
}
```

```
public class DefaultServerRequestObservationConvention implements ServerRequestObservationConvention {
	@Override
	public String getContextualName(ServerRequestObservationContext context) {
		String httpMethod = context.getCarrier().getMethod().name().toLowerCase();
		if (context.getPathPattern() != null) {
			return "http %s %s".formatted(httpMethod, context.getPathPattern());
		}
		return "http " + httpMethod;
	}
}
```

```
class SimpleObservation implements Observation {
    public void stop() {
        if (this.convention != null) {
            this.context.addLowCardinalityKeyValues(this.convention.getLowCardinalityKeyValues(this.context));
            this.context.addHighCardinalityKeyValues(this.convention.getHighCardinalityKeyValues(this.context));
            String newContextualName = this.convention.getContextualName(this.context);
            if (StringUtils.isNotBlank(newContextualName)) {
                this.context.setContextualName(newContextualName);
            }
        }
}
```

**Comment by chicobento** [comment]
I just came across this issue on my environment and can confirm the same behavior.
With the current implementation, span name-based Samplers will not work.

**Comment by gdromero** [comment]
Same issue here!

![span-name-empty](https://github.com/micrometer-metrics/tracing/assets/4448617/30a6f18b-bfd0-4374-a893-2757149466f3)

**Comment by marcingrzejszczak** [comment]
You can create your own handler https://github.com/micrometer-metrics/tracing/blob/v1.1.3/micrometer-tracing/src/main/java/io/micrometer/tracing/handler/PropagatingReceiverTracingObservationHandler.java for receiving and for sending https://github.com/micrometer-metrics/tracing/blob/v1.1.3/micrometer-tracing/src/main/java/io/micrometer/tracing/handler/PropagatingSenderTracingObservationHandler.java . There you can customize how you create the spans

**Comment by chicobento** [comment]
Hi @marcingrzejszczak , I played a little with a custom _PropagatingReceiverTracingObservationHandler_ but still couldn't make it work.

Idea was to override customizeExtractedSpan to set the _contextualName_ before the [start()](https://github.com/micrometer-metrics/tracing/blob/v1.1.3/micrometer-tracing/src/main/java/io/micrometer/tracing/handler/PropagatingReceiverTracingObservationHandler.java#L74) method is triggered:

```java
public class SpanNamePropagatingReceiverTracingObservationHandler<T extends ReceiverContext>
        extends PropagatingReceiverTracingObservationHandler<T>
{

    private final ObservationConvention convention = new DefaultServerRequestObservationConvention();

    /**
     *
     * @param tracer
     * @param propagator
     */
    public SpanNamePropagatingReceiverTracingObservationHandler(final Tracer tracer, final Propagator propagator)
    {
        super(tracer, propagator);
    }

    @SuppressWarnings ("unchecked")
    @Override
    public Span.Builder customizeExtractedSpan(final T context, final Span.Builder builder)
    {
        context.setContextualName(convention.getContextualName(context));
        builder.name(context.getContextualName() != null ? context.getContextualName() : context.getName());
        return builder;
    }

}
```

I ran into the following issues:
1. _context.getContextualName()_ was returning null hence I was always getting context.getName() which is http.server.requests. Fixed by injecting _DefaultServerRequestObservationConvention_
2. Now [DefaultServerRequestObservationConvention.getContextualName](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/server/observation/DefaultServerRequestObservationConvention.java#L86) wont concatenate the pathPattern because it hasn't been set yet. I always get "_http method_"

So as far as I understood, the _PropagatingReceiverTracingObservationHandler.start_ method is triggered very early by the ServerHttpObservationFilter while the _pathPattern_ information is populated only later on by [RequestMappingInfoHandlerMapping](https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/RequestMappingInfoHandlerMapping.java#L180) via Spring MVC _DispatcherServlet_.

Any ideas ?

**Comment by chicobento** [comment]
Yeap, regexp or any other parsing will be very challenging and limited.

Some alternatives that I can think of (not sure how complex, acceptable or bizarre they are) as Im not familiar with the whole codebase:

1. trigger the same RequestMappingInfoHandlerMapping algorithm earlier, before ServerHttpObservationFilter - my guess is that it is complex and does not worth it
2. after the RequestMappingInfoHandlerMapping algorithm is triggered by _DispatcherServlet.doService_ set the span name and give another 'chance' to re-evaluate the sampling decision: tradeoff is that you may end-up losing some information or some nanos (time between ServerHttpObservationFilter and the RequestMappingInfoHandlerMapping) but I guess that it is acceptable for ppl willing to use JaegerRemoteSampler - better than not supporting this at all

**Comment by jtorkkel** [comment]
Hi, 

There is no access to requests but path can be found from getHighCardinalityKeyValue.
Unfortunately customizeExtractedSpan cannot modify the spanName set by extract. 

extract use SdkSpanBuilder/OtelSpanBuilder (from sdkTracer), which cannot be exported.
customizeExtractedSpan use micrometer spanBuilder. 
Debugger shows that builder contains "delegate" which contain spnName". customizeExtractedSpan builder can set 
"name" or attributes, which set attributes to delegates, not spnName. But these are not used Thus "<unspecified span name> is passed to ShouldSample

```
    @Override
    public Span.Builder customizeExtractedSpan(final T context, final Span.Builder builder) {
        String path = context.getHighCardinalityKeyValue("http.url").getValue();
        // set name, not delegate/spnName
        builder.name(context.getContextualName() != null ? context.getContextualName() : path);
        // no access to delegate spanName which is build using SdkSpanBuilder from package io.opentelemetry.sdk.trace;
        builder.tag("spanName", path); // adds attribute to delegate
        return builder;
    }
```


![customizeExtractedSpan](https://github.com/micrometer-metrics/tracing/assets/19704268/8d9e0f79-e1e2-49c5-a507-2985681dcc3e)

```
        ((SdkSpanBuilder)((OtelSpanBuilder)builder).delegate).spanName
```

onStart can be override, but it does not help, only extract can set spnName, extract cannot be override as no access to tracer.

Sound that provided customization cannot customize the spnName used by samper.

**Comment by jtorkkel** [comment]
I did mode checking. 

extract (OtelPropagator.java) use SdkTracer SpanBuilder which support contructor with SpanName. Unfortunately it is set permanently to SpanName="" 

customizeExtractedSpan use OtelSpanBuilder and its constructor does not allow setting SpanName. spanName set to "".
Both builder lack method to modify SpanName

Seems that customizeExtractedSpan/OtelSpanBuilder only allow modifying kind and tags/attributes (modify delegate). Method for modifying remoteIpAndPort and remoteServiceName end up into 1 or two attributes of delegate. 
Name method set name but it is unused and not modifying delegate.

Method for changing SpanName is missing from both builders.

**I think that method/constructor for modifying spanName should be added to builders.**

I tested this using this customizeExtractedSpan
```
    public Span.Builder customizeExtractedSpan(final T context, final Span.Builder builder) {
        String path = context.getHighCardinalityKeyValue("http.url").getValue();

        builder.name(context.getContextualName() != null ? context.getContextualName() : "x"+path);
        // no access to delegate spanName which build using SdkSpanBuilder from package io.opentelemetry.sdk.trace;
        builder.tag("name", "xx"+path); // adds attribute to delegate
        builder.tag("spanName", "xxx"+path); // adds attribute to delegate
        builder.kind(PRODUCER);
        builder.remoteIpAndPort("1.1.1.1", 12345);
        builder.remoteServiceName("xxx");

        // Not possible to set spanName when new builder is created.
        //     @Override
        //    public Span.Builder spanBuilder() {
        //        return new OtelSpanBuilder(this.tracer.spanBuilder(""));
        //    }
        Span.Builder newBuilder = this.tracer.spanBuilder().name("xxxx+path");

        return builder;
    }

```
From the picture it can be seen that kind can be set correctly, and rest set to tag/attributes.

![customizeExtractedSpan3](https://github.com/micrometer-metrics/tracing/assets/19704268/ddcdb0b0-4d89-4fc0-808e-f2d5780e6749)

**Comment by marcingrzejszczak** [comment]
I think this is a bug in tracing. What we should do is to store al the data in the builder and on `startSpan()` actually call the OTel's `SpanBuilder`. That way the name will have already been updated and passed to the builder and then samplers can do their thing. WDYT?

**Comment by marcingrzejszczak** [comment]
Can you check the latest snapshots once their out if things are working fine now?

**Comment by jtorkkel** [comment]
> Can you check the latest snapshots once their out if things are working fine now?

I can try but I might have issues. At least earlier our firewall has prevented downloading springBoot snapshots. But I can download the JARs directly and add it to the BOM directly instead of adding maven dependencies.

I assume this is the JAR which has all the changes?
https://repo.spring.io/artifactory/snapshot/io/micrometer/micrometer-tracing-bridge-otel/1.1.5-SNAPSHOT/micrometer-tracing-bridge-otel-1.1.5-20230818.122108-6.jar

I will try latest by Monday.

**Comment by marcingrzejszczak** [comment]
Yeah, I am more than certain it will work (famous last words). That's because we know store the name and create an Otel builder using that name. Previously we would create a builder with no name and then update span's name.

**Comment by jtorkkel** [comment]
Now seems to work with snapshot. 
customizeExtractedSpan can set the name which customize the spanName used by shouldSample.
Thanks

**Comment by marcingrzejszczak** [comment]
Thanks for checking it out!
