### ISSUE TITLE
`Tracer` methods don't use the `Tracer#currentTraceContext`

### ISSUE THREAD

**Issue by jrhee17** [micrometer-metrics/tracing#268]
I've been working for the past few days looking into `micrometer-tracing`, and had a question on the behavior of `Tracer#currentTraceContext`.

Looking at the `BraveTracer` implementation, it seems like the behavior for `BraveTracer#nextSpan` delegates directly to `brave`'s `Tracer` implementation (which may be using a different `CurrentTraceContext)`.

So,
```
tracer.currentTraceContext().newScope(null)
```
may use a different `CurrentTraceContext` implementation from 
```
tracer.withSpan(null)
```
depending on how `tracer` is implemented.

e.g.
```
private static class TestCurrentTraceContext extends CurrentTraceContext {

    @Override
    public TraceContext get() {
        throw new RuntimeException("shouldn't be used");
    }

    @Override
    public Scope newScope(TraceContext context) {
        throw new RuntimeException("shouldn't be used");
    }
}

@Test
void inconsistentContexts() {
    final SpanCollector collector = new SpanCollector();

    final TestCurrentTraceContext context = new TestCurrentTraceContext();
    final Tracing tracing = Tracing.newBuilder()
                                   .addSpanHandler(collector)
                                   .currentTraceContext(context)
                                   .sampler(Sampler.ALWAYS_SAMPLE)
                                   .build();

    final BraveCurrentTraceContext tracingContext =
            new BraveCurrentTraceContext(ThreadLocalCurrentTraceContext.create());
    final BraveTracer tracer = new BraveTracer(tracing.tracer(), tracingContext);

    // doesn't throw
    try (Scope scope = tracer.currentTraceContext().newScope(null)) {
        assertThat(scope).isNotNull();
    }

    // throws
    try (SpanInScope scope = tracer.withSpan(null)) {
        assertThat(scope).isNotNull();
    }
}
```

The same can be said about the `otel` implementation as well.

We've been providing a custom `CurrentTraceContext` to users from our library, so I'm thinking this behavior may confuse users.
I appreciate any advice 😄

**Comment by marcingrzejszczak** [comment]
Hey @jrhee17 , has this been already addressed with what we did with the Armeria PR?

**Comment by jrhee17** [comment]
> Hey @jrhee17 , has this been already addressed with what we did with the Armeria PR?

I thinks so! Let me go ahead and close this.
