### ISSUE TITLE
Tracing is lost when using WebClient (reactor-http-nio threads)

### ISSUE THREAD

**Issue by mziemba** [micrometer-metrics/tracing#271]
Hi,
we are migrating our services from Spring Boot 2.7 to 3.0 and we noticed we are losing tracing information (trace, span, and baggage) when using WebClient. Looks like the problem occurs when application switches from a Jetty server thread to reactor-http-nio thread. Am I doing something wrong, or should this work out-of-the-box without explicitly customizing the reactor-http-nio thread pool executor?

micrometer-tracing version: 1.1.1

```
[INFO] [2023-06-02 22:28:24,158] [demo-service,647a50e8a0a448a9d729afe03e174ee9,d729afe03e174ee9,demo-client] [qtp2118413714-24] d.DemoController: Starting to process request in controller
[INFO] [2023-06-02 22:28:24,165] [demo-service,647a50e8a0a448a9d729afe03e174ee9,d729afe03e174ee9,demo-client] [qtp2118413714-24] d.DemoController: Finishing to process request in controller
[INFO] [2023-06-02 22:28:27,279] [demo-service,,,] [reactor-http-nio-2] d.DemoController: This log is missing tracing information!!!
[INFO] [2023-06-02 22:28:27,279] [demo-service,,,] [reactor-http-nio-2] d.DemoController: This log is missing tracing information!!!
```

Reproducer: https://github.com/mziemba/micrometer-tracing-webclient-issue

**Comment by mziemba** [comment]
Is this a duplicate of https://github.com/micrometer-metrics/micrometer/issues/3833?

**Comment by jonatan-ivanov** [comment]
I don't think so, it seems you are creating a `WebClient` on your own, please check the docs of `WebClient`, you need to create a `@Bean` from it using the `WebClient` builder: https://docs.spring.io/spring-framework/reference/integration/observability.html#observability.http-client.webclient

**Comment by mziemba** [comment]
I am injecting `WebClient.Builder` bean auto-configured by Spring Boot. Having said that, it looks like adding `Hooks.enableAutomaticContextPropagation()` solved the issue.

Thank you

**Comment by mziemba** [comment]
Hi,
can this issue be re-opened please? Adding `Hooks.enableAutomaticContextPropagation()` fixed propagation of trace and span, but not baggage, I've updated the reproducer to reflect that:

```
[INFO] [2023-08-14 17:47:17,599] [demo-service,999927cdec71191383f28bee90fc0658,208337a4de174dbf,demo-client,efbbd7b1-cfa4-4572-b988-d95a21728d2f] [qtp627519623-24] d.DemoController: Starting to process request in controller
[INFO] [2023-08-14 17:47:17,609] [demo-service,999927cdec71191383f28bee90fc0658,208337a4de174dbf,demo-client,efbbd7b1-cfa4-4572-b988-d95a21728d2f] [qtp627519623-24] d.DemoController: Finishing to process request in controller
[INFO] [2023-08-14 17:47:20,856] [demo-service,999927cdec71191383f28bee90fc0658,208337a4de174dbf,,] [reactor-http-nio-2] d.DemoController: This log is missing baggage information!!!
[INFO] [2023-08-14 17:47:20,856] [demo-service,999927cdec71191383f28bee90fc0658,208337a4de174dbf,,] [reactor-http-nio-2] d.DemoController: This log is missing baggage information!!!
```

https://github.com/mziemba/micrometer-tracing-webclient-issue

**Comment by mziemba** [comment]
Hi Marcin, thanks for your answer.
In my case, when I set the baggage in a filter and want it to be available for the whole request, where is the best place to close it?

I've tried to do it after `filterChain.doFilter(request, response)` but it didn't change the outcome - it is still not being propagated into logs.

**Comment by shakuzen** [comment]
Check out the [Spring Framework instrumentation](https://github.com/spring-projects/spring-framework/blob/e685ff0416f03243d1eae900f080b26caaefd449/spring-web/src/main/java/org/springframework/web/filter/ServerHttpObservationFilter.java#L102-L126) using a OncePerRequestFilter for inspiration. You'll want to use try-finally blocks or try-with-resources to ensure scopes are closed.
