### ISSUE TITLE
W3C parentId not correctly used?

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [micrometer-metrics/tracing#291]
Hi I just tried the micrometer tracing tool and most of it works good so far, but I stumbled across one thing with the parent-id from the w3c spec:

```
3.2.2.4 parent-id

This is the ID of this request as known by the caller (in some tracing systems, this is known as the span-id, where a span is the execution of a client request). It is represented as an 8-byte array, for example, 00f067aa0ba902b7. All bytes as zero (0000000000000000) is considered an invalid value.

Vendors MUST ignore the traceparent when the parent-id is invalid (for example, if it contains non-lowercase hex characters).
```

from my understanding the parent-id should be used as span-id at the vendor system. So if I have a frontend and a backend the backend should accept the parent-id as spanId. But if I receive this header at my backend:

`00-00000000000000004df3f94a268e97fa-ea803a6ca72917bd-01`

only the trace-id is correctly applied to my log. The parent-id is not used as span-id and a complete new span-id is generated:

the logging pattern is: `logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]`

and the result in the log looks like this:
```
2023-06-20 07:41:18.614 DEBUG [backend,4df3f94a268e97fa,e4f0815c4627dde5]
```

as you can see, the parent-id is not used as spanId. Am I understanding something incorrectly in the w3c spec or is this a bug?

**Comment by Captain-P-Goldfish** [comment]
We are importing
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
```
that comes with
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-sleuth-brave</artifactId>
</dependency>
```
So it seems that it is the brave bridge if I am not mistaken

**Comment by marcingrzejszczak** [comment]
Why are you mentioning Sleuth in the Micrometer Tracing repo?

**Comment by Captain-P-Goldfish** [comment]
I was positive that it was using micrometer-tracing under the hood. But I checked again and it is using micrometer-core not tracing. That's why I thought that micrometer would be the correct address for this issue. Sorry for this confusion
