### ISSUE TITLE
Add TracedRunnable and TracedCallable

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/tracing#293]
Similarly to [`TraceRunnable`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceRunnable.java) in Sleuth, I think we could make the lives of those users who wants to switch threads simpler in some scenarios by providing `TracedRunnable` and `TracedCallable` components that will propagate the context and create a new `Span` for tasks running on different threads. Additionally, maybe we can create components that are not starting new `Span`s but just propagating the context (open `Scope`). The use-case is something like this: https://micrometer.io/docs/tracing#_micrometer_tracing_examples

See: https://github.com/micrometer-metrics/micrometer/issues/3881

**Comment by vasantteja** [comment]
I am working on adding ObservedRunnable and ObservedCallable. During that process I came across [this](https://github.com/spring-projects/spring-boot/issues/34622). I believe adding TraceRunnable and exposing an executor similar to LazyTraceExecutor will be a good design. If not should can we expose this in ContextExecutorService. Please let me know your thoughts and correct me if I am wrong.

**Comment by vasantteja** [comment]
Also can I please work on this also along with ObservedRunnable.

**Comment by jonatan-ivanov** [comment]
I think that could be step two on top of `TraceRunnable`. But I'm curious about @marcingrzejszczak's opinion.

I assigned this issue to you.

**Comment by marcingrzejszczak** [comment]
So let's discern two things here

1) Context Propagation
2) Span creation

We already have the 1) done via https://github.com/micrometer-metrics/context-propagation and its methods. I understand that we would like to have some helper methods to create new observations around `Runnable`, `Callable` and `Executor`s and `ExecutorService`s ? 

I think those are so specific that we can't really create anything out of the box for them (I think doing that for Sleuth wasn't the best idea). How would we call the observations? What would be the low and high cardinality tags?

**Comment by krshna-dtdl** [comment]
I have this code:

`    public static ExecutorService newFixedThreadPool(final int corePoolSize) {
        final ExecutorService service = Executors.newFixedThreadPool(corePoolSize);
        return ContextExecutorService.wrap(service, ContextSnapshot::captureAll);
    }`
    
 I need to submit multiple tasks to it. Now I need to propogate some key-value pairs to each task.
 
 Those key values will be different for each task.
 
 Once that task gets those key values, it will be set in ThreadLocal/Use Them for some purpose.
 
 How can I do it?
 
 I tried to implement ThreadLocalAccessor but that is propagating wrong key values for each task.
 
 @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Do you want to create an observation around those scheduled tasks or propagate baggage?

**Comment by krshna-dtdl** [comment]
> Do you want to create an observation around those scheduled tasks or propagate baggage?

We need to propagate some key values to each thread.

So let's say there's a for loop in which we are submitting the task to the executor service and before submission that key value might get changed. So that updated value needs to be propagated. Tried this with ThreadLocalAccessor but that propagates the wrong key value.

**Comment by marcingrzejszczak** [comment]
So just write custom wrapper around the executor that will take the current observation and modify its key value.

**Comment by marcingrzejszczak** [comment]
Ping?
