### ISSUE TITLE
CurrentTraceContext.context()t is null in downstream

### ISSUE THREAD

**Issue by maxio89** [micrometer-metrics/tracing#299]
I have a code like this and injected `CurrentTraceContext` from **Micrometer Tracing**:

```
        dataSourceClient.retrieveCount(categoryConfig.getCountEndpoint()) <-- this invokes WebClient from Reactor
                .map(CountResponseDTO::getTotalSize) <- here currentTraceContext.context() exists
                .flatMap(count -> createIndex(config, timestamp, count) <- starting from here it returns a `null`
                        .map(indexName -> SyncContext.builder()
                                .config(config)
                               .build()))
                .flatMap(this::publishMessages)
                .flatMap(this::doSomethingElse)
                .subscribe();
```

Config and dependencies:

```
@Configuration
public class TracingConfig {

    @Bean
    public CurrentTraceContext currentTraceContext(brave.propagation.CurrentTraceContext currentTraceContext) {
        return new BraveCurrentTraceContext(currentTraceContext);
    }

    @Bean
    public Tracer tracer(CurrentTraceContext currentTraceContext, Tracing tracing) {
        brave.Tracer braveTracer = tracing.tracer();
        BraveTracer braveTracer1 = new BraveTracer(braveTracer, currentTraceContext, new BraveBaggageManager());
        ContextRegistry.getInstance().registerThreadLocalAccessor(new ObservationAwareSpanThreadLocalAccessor(braveTracer1));
        return braveTracer1;
    }

}
```

```
       <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-bom</artifactId>
                <version>2022.0.8</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-core-micrometer</artifactId>
                <version>1.0.7</version>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-bom</artifactId>
                <version>1.1.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-bridge-brave</artifactId>
                <version>1.1.2</version>
            </dependency>
```

We use Spring Boot 3.1.1 with Reactor framework.

Any idea why currentTraceContext.context() is null in the first flatMap operator?

From what I can see on debug the Observation is closed after first http call, but I don't know if this is normal behaviour and I should still expect context available.

Thanks for help!

**Comment by marcingrzejszczak** [comment]
cc @chemicL

**Comment by chemicL** [comment]
Please share the code which invokes webClient to see which API methods are in use.

**Comment by maxio89** [comment]
```
 Mono<CountResponseDTO> retrieveCount(Endpoint countEndpoint) {
        return webClient.method(countEndpoint.getMethod())
                .uri(countEndpoint.getPath())
                .retrieve()
                .bodyToMono(CountResponseDTO.class)
                .onErrorResume(WebClientErrorsUtils::handleError)
                .retryWhen(Retry.backoff(MAX_RETRIES, Duration.ofSeconds(1)));
    }
```

**Comment by chemicL** [comment]
Thank you. And what does `createIndex` do? Is the context non-`null` in the `flatMap` before calling this method and `null` after `createIndex` resumes?

**Comment by maxio89** [comment]
FullSyncService:
```
private Mono<String> createIndex(Config config, String timestamp, Long count) {
        final var metadata = Index.Metadata.builder()
                .count(count)
                .traceId(tracer.currentTraceContext().context().traceId()) <-- NPE here
                .build();
        return indexService.createIndex(config.getName(), timestamp, metadata);
```

IndexService:
  ```
  Mono<String> createIndex(String categoryName, String suffix, Index.Metadata metadata) {
        var indexName = getIndexName(categoryName, suffix);
        final Map<String, Object> mapping = new HashMap<>();
        mapping.put("_meta", metadata);
        return indexDAO.createIndex(indexName, mapping)
                .thenReturn(indexName);
    }
```

IndexDao:
```
Mono<Void> createIndex(String indexName, Map<String, Object> mapping) {
        return reactiveIndicesClient.createIndex(indexName, mapping).then();
    }
```

ReactiveIndicesClient:

    public Mono<CreateIndexResponse> createIndex(String indexName, byte[] indexConfig, Map<String, Object> meta) {

        return Mono.fromSupplier(() -> {
            final var requestBuilder = new CreateIndexRequest.Builder();
            requestBuilder.index(indexName);
            ...
            return requestBuilder.build();
        })
                .flatMap(request -> Mono.fromFuture(indicesClient.create(request))) 
                .subscribeOn(scheduler); <-- new BoundedElastic scheduler
    }

`indicesClient` from above is from **elasticsearch-java:7.17.10** which uses **Apache httpasyncclient:4.1.5** and that might be a problem, because it's not instrumented by default. Right?
Previously we used `TracingHttpAsyncClientBuilder`  from **brave-instrumentation-httpasyncclient**. 
Are there any alternatives or do we need to instrument this manually using some HTTP interceptors or something?

**Comment by chemicL** [comment]
That's what I expected :) I see two options:

- consider [Spring Data ElasticSearch](https://github.com/spring-projects/spring-data-elasticsearch) (`ReactiveElasticsearchClient`)
- change the below code in `ReactiveIndicesClient#createIndex`:

        // Mono.fromFuture(indicesClient.create(request)) ->
        Mono.fromFuture(indicesClient.create(request)).contextWrite(Function.identity())

**Comment by maxio89** [comment]
Actually the context is null right before calling a `createIndex` so it changed nothing I'm afraid.

**Comment by chemicL** [comment]
Please try creating an isolated reproducer, free of external dependencies: just WebClient, skip the call to the elasticsearch client - replace it with e.g. `Mono.just(dummy)` and we can analyze it.

**Comment by maxio89** [comment]
That's exactly what I'm planning to do. Thanks.

**Comment by maxio89** [comment]
I was able to reproduce this problem in example app.
https://github.com/maxio89/demo-tracing/blob/master/src/main/java/com/example/demo/ExampleController.java

```

@RestController
@RequestMapping("/tracing")
public class ExampleController {

	@Autowired
	CurrentTraceContext context;
	@Autowired
	WebClient webClient;

	@GetMapping("/webclient")
	public Mono<Void> getWebclient() {
		return Mono.just(1)
				.doOnSuccess(a -> WebClient.create().get()
						.uri("https://httpbin.org/get")
						.retrieve()
						.bodyToMono(String.class)
						.doOnNext(next -> {
            /* context is null here --> */            System.out.println(context.context());
						})
						.subscribe())
				.then();
	}

}
```

So the problem is related with the thing we do subscribing to another stream. 
We have a nested streams and the context stopped propagating after migration from Sleuth to Micrometer Tracing.
Adding                 `.contextWrite(Context.of(TraceContext.class, currentTraceContext.context()))` on inner stream doesn't change anything.

**Comment by chemicL** [comment]
Two issues @maxio89 in your implementation:

1. `WebClient.create()` -> this should be replaced to use the injected `webClient` instance and not create a new, bare one.
2. The fact you're creating an unattached `Publisher`, to which you manually subscribe and abandon the reference -> This chain has no `Context` attached, meaning you can't expect the trace context to be present.

Does that fix the issue you're observing?

**Comment by maxio89** [comment]
> Two issues @maxio89 in your implementation:
> 
> 1. `WebClient.create()` -> this should be replaced to use the injected `webClient` instance and not create a new, bare one.
> 2. The fact you're creating an unattached `Publisher`, to which you manually subscribe and abandon the reference -> This chain has no `Context` attached, meaning you can't expect the trace context to be present. I'm not sure about the mechanics here, but do you have a `ThreadLocalAccessor` for `TraceContext.class` ? If not, then I wouldn't expect anything to be propagated even if you add the `contextWrite`. AFAIR (and @marcingrzejszczak can correct me) the trace context is just a derivative of an `Observation` being in scope.
> 
> Does that fix the issue you're observing?

1. Yeah, you right, but it doesn't change anything.
2. Do you mean adding something like this `ContextRegistry.getInstance().registerThreadLocalAccessor(new ObservationAwareSpanThreadLocalAccessor(braveTracer));`? 

I updated my examples. It's even worse, because context is null at the beginning of controller method.

**Comment by chemicL** [comment]
Your code still has a few minor issues, but consider the following changes:

```
return Mono.just(1)
				.flatMap(a -> webClient.get() // <1>
						.uri("http://www.google.pl/")
						.retrieve()
						.bodyToMono(String.class)
						.doOnNext(next -> {
							/* context is null here -> */ System.out.println(context.context());
						})) // <2>
				   .then();
```
				   
1. `flatMap` instead of `doOnNext`
2. no `subscribe()` - as mentioned, this disconnects the chain from the one that has an Observation attached!

**Comment by maxio89** [comment]
The subscribe() was there, because we wanted to return response to the client immediately and then run some background logic asynchronously.

**Comment by chemicL** [comment]
@maxio89 I suppose the best place to ask questions is the [Micrometer Slack](https://github.com/micrometer-metrics/tracing#join-the-discussion).
