### ISSUE TITLE
Tracing and core version alignment (Discussion)

### ISSUE THREAD

**Issue by checketts** [micrometer-metrics/tracing#3]
Very interesting to see micrometer tracing initial release! Since it relies on micrometer-core v2. Would there be much sense to have the version parallel?

**Comment by marcingrzejszczak** [comment]
What do you mean by putting the versions in parallel? Like that we start with 2.0.0 ? That's not planned really.

**Comment by checketts** [comment]
Right. Similar to how all Jackson modules and even all Micrometer registries stay on the same version, even if that submodule hasn't been changed.

Alternatively providing a BOM that keeps the compatible versions in sync is needed. While Spring's BOM probably would be good enough (for me). Not everyone uses Spring and they might need another option.

I don't feel super strongly about this, but figured it would be good to discuss and be intentional if to try to avoid incompatible versions or confusion in the future.

**Comment by marcingrzejszczak** [comment]
We have a BOM for tracing https://github.com/micrometer-metrics/tracing/tree/main/micrometer-tracing-bom that takes in micrometer in https://github.com/micrometer-metrics/tracing/blob/main/dependencies.gradle#L29. So it's enough for you to know the micrometr-tracing version and you get the proper micrometer version

**Comment by checketts** [comment]
That sounds great! Thanks.
