### ISSUE TITLE
Missing traceId in error log

### ISSUE THREAD

**Issue by wapkch** [micrometer-metrics/tracing#301]
As mentioned in https://github.com/spring-projects/spring-framework/issues/30675

The trace id in error log is missing after upgrading from Spring Boot 2 to Spring Boot 3.

After looking into it, i found that add a tomcat TraceValve like Spring Cloud Sleuth does can solve the problem. I'm not sure whether this should be provided by default?

Sample:
https://github.com/wapkch/web-tracing-log-demo

**Comment by jonatan-ivanov** [comment]
There is not much we can do for this on Micrometer Tracing side, please see these issues:
- https://github.com/spring-projects/spring-framework/issues/29848
- https://github.com/spring-projects/spring-framework/issues/29398

As a workaround, you can create an error handler and signal the error on the Observation: [example](https://github.com/jonatan-ivanov/teahouse/blob/7883642f7568991934c91990a547dd815e646fae/core/src/main/java/org/example/teahouse/core/error/CommonExceptionHandler.java#L31-L42).
