### ISSUE TITLE
Match OTel semconv version to the SDK version

### ISSUE THREAD

**Issue by raffa134** [micrometer-metrics/tracing#340]
Hello team! 

I'm encountering a dependency conflict issue with Micrometer Tracing Bridge Otel 1.1.3. Here's the error message:

```
[ERROR]       +-io.micrometer:micrometer-tracing-bridge-otel:jar:1.1.3:compile\n
[ERROR]         +-io.opentelemetry:opentelemetry-sdk-trace:jar:1.25.0:compile
[ERROR]           +-io.opentelemetry:opentelemetry-semconv:jar:1.25.0-alpha:runtime
[ERROR] and
[ERROR]       +-io.micrometer:micrometer-tracing-bridge-otel:jar:1.1.3:compile
[ERROR]         +-io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-semconv:jar:1.24.0-alpha:compile
[ERROR]           +-io.opentelemetry:opentelemetry-semconv:jar:1.24.0-alpha:compile
```

There seems to be a conflict between different versions of the `opentelemetry-semconv` library being pulled in. 
Resolving this issue might require a change on your side. However, if you have an alternative solution or suggestion, please feel free to let me know. Thank you!

**Comment by jonatan-ivanov** [comment]
Thank you for reporting this, I think there might be another issue we need do deal with when we fix this one: as far as I understand [`io.opentelemetry:opentelemetry-semconv`](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-semconv) was moved to [`io.opentelemetry.semconv:opentelemetry-semconv`](https://search.maven.org/artifact/io.opentelemetry.semconv/opentelemetry-semconv) and the former [will be deprecated](https://github.com/open-telemetry/opentelemetry-java/pull/5786).

**Comment by shakuzen** [comment]
I opened #343 for the move to the new coordinates.
