### ISSUE TITLE
Documentation shows deprecated code

### ISSUE THREAD

**Issue by pvandenbroucke** [micrometer-metrics/tracing#341]
Hello,

On this [page](https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#async-instrumentation), the code snippet refers to deprecated code (`ContextSnapshot::captureAll`).

Could you update the documentation with the recommended way to follow and additional information ? 

Thanks in advance

**Comment by marcingrzejszczak** [comment]
I've updated the wiki so that you check the docs here https://micrometer.io/docs/contextPropagation with the latest samples.

You can use the following code for reference

```java
ContextSnapshot snapshot = ContextSnapshotFactory.builder().build().captureAll();
```

**Comment by pvandenbroucke** [comment]
Thanks for the quick reply
