### ISSUE TITLE
Trace being lost between @RabbitListener and webClient

### ISSUE THREAD

**Issue by Jojoooo1** [micrometer-metrics/tracing#342]
Hi,

I have created a simple project that is reading message from rabbitmq using @RabbitListener and a webClient (created by a Builder) that is sending the message content to an external api. This is basically a webhook microservice.

When I receive the rabbitmq message and passes it to the webclient the traces are not passed downstream event if Hooks.enableAutomaticContextPropagation() is set.

Here a working example: https://github.com/Jojoooo1/spring-microservice-webhook-reactive

I have tried with many version from Spring boot 3.0. Spring boot 2.7 and sleuth was working correctly.

**Comment by marcingrzejszczak** [comment]
Here you have an example of a Rabbitmq consumer https://github.com/micrometer-metrics/micrometer-samples/tree/main/rabbitmq-consumer and Rabbitmq producer https://github.com/micrometer-metrics/micrometer-samples/tree/main/rabbitmq-producer . Can you see if that helps?

**Comment by Jojoooo1** [comment]
Hi @marcingrzejszczak thanks for the help! The trace is actually being created automatically from the @RabbitListener without any problem. 
The problem come from the switching context to the webclient. Within the exchangeToMono function the currentTraceContext is null and somehow the RabbitListener trace context is not passed. 

```
    return this.webClient
        .post()
        .uri(url)
        .bodyValue(requestBody)
        .exchangeToMono(this::defaultResponseHandler)
```

**Comment by marcingrzejszczak** [comment]
Summoning @chemicL

**Comment by Jojoooo1** [comment]
fixed by injecting builder and using Spring Boot 3.2.0-M3
