### ISSUE TITLE
Move to io.opentelemetry.semconv:opentelemetry-semconv

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/tracing#343]
[`io.opentelemetry:opentelemetry-semconv`](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-semconv) was moved to [`io.opentelemetry.semconv:opentelemetry-semconv`](https://search.maven.org/artifact/io.opentelemetry.semconv/opentelemetry-semconv) and the former [will be deprecated](https://github.com/open-telemetry/opentelemetry-java/pull/5786).

Edit: That will only impact 1.2.x though, not 1.1.x what this issue should be for.
Edit2: Moving to the new semconv artifact will be the problem of the next release (1.2.0-RC1) .

_Originally posted by @jonatan-ivanov in https://github.com/micrometer-metrics/tracing/issues/340#issuecomment-1710656093_

**Comment by marcingrzejszczak** [comment]
Actually this is only used by https://github.com/micrometer-metrics/tracing/issues/350 . If we removed those (again, Boot is not using the client and server) then we would have fewer deps to take care of

**Comment by marcingrzejszczak** [comment]
The way I did it is actually a breaking change cause we don't include the deprecated dependency anymore. @wilkinsona is this actually ok from point of view e.g. Boot or should we add both dependencies and remove the deprecated one in e.g. 1-2 minors?

**Comment by wilkinsona** [comment]
I'll have a better feel for it once we've moved to snapshots next week, but I think that's probably OK. My expectation is that anyone who really needs the deprecated one can add the dependency directly. We consider that kind of easily fixed problem to be fine for a new minor release of Boot.
