### ISSUE TITLE
Baggage not propagated to downstream service when using reactive chain

### ISSUE THREAD

**Issue by swereddy** [micrometer-metrics/tracing#377]
Having below code does not propagate baggage to downstream with otel bridge

```
return getBaggage().flatMap { bagMap ->
            val baggageBuilder = Baggage.builder()
            bagMap.forEach { (key, value) -> baggageBuilder.put(key, value) }
            baggageBuilder.build().makeCurrent().use {
                //make a call to downstream webclient is used
            }
        }
```

// getBaggage returns a Mono.

**Comment by marcingrzejszczak** [comment]
Can you test against the latest snapshots? Also can you provide a sample that reproduces this issue?

**Comment by swereddy** [comment]
@marcingrzejszczak  - I found that baggage and tracing works with producer-reactive  -> non reactive consumer but does not work with producer-reactive -> reactive-consumer. 
Producer reactive sample code - https://github.com/swereddy/producer-reactive
Consumer reactive sample code - https://github.com/swereddy/micrometer-samples/tree/reactive-sample
