### ISSUE TITLE
Test for #363

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/tracing#397]
> Looking at the commit that resolved this, it doesn't appear there's anything preventing a regression like this from sneaking back in.
> As this is quite a fundamental thing, could you ensure it's properly tested?

_Originally posted by @vpavic in https://github.com/micrometer-metrics/tracing/issues/363#issuecomment-1752658058_

**Comment by jonatan-ivanov** [comment]
Fixed in #421
