### ISSUE TITLE
Manually created baggage fields do not propagate across threads using ObservationAwareSpanThreadLocalAccessor

### ISSUE THREAD

**Issue by wapkch** [micrometer-metrics/tracing#412]
A sample is like this, the value of baggage field 'tenant' is expected to propagated correctly. But it's `null` now.
```css
management.tracing.baggage.remote-fields=tenant
```

```java
@SpringBootApplication
public class MicrometerTracingDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(MicrometerTracingDemoApplication.class, args);
    }

    @Bean
    CommandLineRunner commandLineRunner(ObservationRegistry observationRegistry, Tracer tracer) {
        return args -> {
            ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
            executor.setTaskDecorator(runnable ->
                ContextSnapshotFactory.builder().build().captureAll().wrap(runnable));
            executor.initialize();

            ScopedSpan scopedSpan = tracer.startScopedSpan("test");
            try (BaggageInScope baggageInScope = tracer.getBaggage("tenant").makeCurrent("tenant")) {
                executor.submit(() -> {
                    String tenant = tracer.getBaggage("tenant").get();
                    // tenant should not be null
                    System.out.println(tenant);
                });
            } finally {
                scopedSpan.end();
            }
        };
    }

}

@Component
class Registrar implements SmartInitializingSingleton {

    @Autowired
    ObservationRegistry observationRegistry;

    @Autowired
    Tracer tracer;

    @Override
    public void afterSingletonsInstantiated() {
        ContextRegistry.getInstance().registerThreadLocalAccessor(
            new ObservationAwareSpanThreadLocalAccessor(observationRegistry, tracer));
    }
}
```

The sample can be found here https://github.com/wapkch/micrometer-tracing-demo/tree/master

**Comment by krodyrobi** [comment]
From playing with the library I noticed that:
- spans get recreated even if `Hooks.enableContextPropagation` is used and executors are instrumented
- since custom baggages are manually created they won't be refreshed or created when thread switching

All of this comes down to a subtle difference in what is available by default in each context.
Controllers/main schedulers wrap code with `Observation.start(..).observe(..)` implicitly for us and that without an active observation nothing gets propagated. Tracing ids take the lack of observation in context as a sign to recreate themselves, while custom baggages can't possibly be re-set as code creating them is not apart of the same library flow.

If you by chance wrap the submit part in the observe scoped lambda do you still see them not propagating?

**Comment by wapkch** [comment]
Actually, only if a `ReceiverContext` is manully passed to Observation, we can do the trick:
```java
ReceiverContext<Map<String, String>> context = new ReceiverContext<>(Map::get);
            context.setCarrier(Map.of("tenant", "tenant"));
            Observation.createNotStarted("test", () -> context, observationRegistry).observe(() -> {
                executor.submit(() -> {
                    String tenant = tracer.getBaggage("tenant").get();
                    // tenant should not be null
                    System.out.println(tenant);
                });
            });
```
The `ReceiverContext` activated the `PropagatingReceiverTracingObservationHandler` which will propagate the baggages.

**Comment by wapkch** [comment]
Yes, use  `Observation.start(..).observe(..)` and explicitly passing a `ReceiverContext` can do the trick:
```java
ReceiverContext<Map<String, String>> context = new ReceiverContext<>(Map::get);
            context.setCarrier(Map.of("tenant", "tenant"));
            Observation.createNotStarted("test", () -> context, observationRegistry).observe(() -> {
                executor.submit(() -> {
                    String tenant = tracer.getBaggage("tenant").get();
                    // tenant should not be null
                    System.out.println(tenant);
                });
            });
```
`ReceiverContext` will activate the PropagatingReceiverTracingObservationHandler which propagates the custom baggages. 

In this way, we don't even need a `ObservationAwareSpanThreadLocalAccessor`, so, i still think ObservationAwareSpanThreadLocalAccessor should work with the `tracer.startScopedSpan(...)` style.

**Comment by wapkch** [comment]
After taking a look into it, i found that when invoking `captureFromThreadLocals`, the `tenant` baggage value in the span is exist:
<img width="1251" alt="image" src="https://github.com/micrometer-metrics/tracing/assets/32868606/a1e6425b-0aa7-46f2-b8db-fa2eaf96dfa7">

But when invoking `setThreadLocals` subsequencely,  the `tenant` baggage value is missing in the restored span:
<img width="1297" alt="image" src="https://github.com/micrometer-metrics/tracing/assets/32868606/bfa6b831-7b17-49bb-9402-bdf55a2d760b">

I'm not sure why now.
