### ISSUE TITLE
Creating Trace with custom Trace Id not working

### ISSUE THREAD

**Issue by bvtk** [micrometer-metrics/tracing#426]
I want to Create a new Span with an custom TraceId. It does not work with the micrometer-tracing-bridge-otel:1.1.6

On the code example the traceContext has the expected passed traceId, But the created Span created with the Spanbuilder gets a new TraceId.

```
val traceContext = this.traceContextBuilder()
    .traceId(traceId)
    .spanId( spanId ?: Random.nextLong().toHexString(HexFormat.Default))
    .sampled(true)
    .build()

  val span = this.spanBuilder()
    .name(name)
    .setParent(traceContext)
    .start()
```

The OtelSpanBuilder only links the parentContext when creating an span with parentContext. But the span gets it's own traceId

![image](https://github.com/micrometer-metrics/tracing/assets/19904930/9b5b0d69-6b7e-4cf2-b311-e8c4b267ddec)

With opentelemetry native it does work

```
val spanContext = SpanContext.create(
      skuGroup.traceId,
      SpanId.fromLong(Random.nextLong()),
      TraceFlags.getSampled(),
      TraceState.getDefault()
    )

    val span = tracer.spanBuilder("maps-worker-process-sku-group")
      .setParent(Context.current().with(Span.wrap(spanContext)))
      .startSpan()
```

It does work, because the io.opentelemetry.sdk.traceSdkSpanBuilder does take the traceId of the parentContext to the new Span:

![image](https://github.com/micrometer-metrics/tracing/assets/19904930/24a78838-0155-4c05-885a-091e5ae15804)

**Comment by bvtk** [comment]
I tried also the same code from above with the micrometer-tracing-bridge-brave. There it works correctly. The span has the same traceId as the created TraceContext.

**Comment by kormik** [comment]
Hi,
I run into the same issue. When I dug into it I found that method `io.micrometer.tracing.otel.bridge.OtelTraceContext#toOtelContext`
always works with the current context, instead of passed context. So there is no way to pass custom context into span builder.
