### ISSUE TITLE
Where to close baggage for a request to a reactive endpoint in a Spring Boot app?

### ISSUE THREAD

**Issue by PiotrMachner** [micrometer-metrics/tracing#427]
Hi Team,
I'm having trouble with premature closing of custom Micrometer Baggage which I described in more detail on SO:
https://stackoverflow.com/questions/77480654/where-to-close-micrometer-baggage-for-a-request-to-a-reactive-endpoint-in-a-spri

What would be the consequences of not closing the baggage at all? Or could you suggest where to best close the baggage for a reactive endpoint of a Spring Boot app?

Thank you very much in advance for your help and time.

**Comment by marcingrzejszczak** [comment]
Can you check the latest snapshots ? I fixed some issues related to passing of baggage. Also can you provide a sample that reproduces this issue?

Also you should not leave the baggage scope not closed, that's because you may pollute thread locals.
