### ISSUE TITLE
@NewSpan annotation not working with micrometer tracing version 1.1.7

### ISSUE THREAD

**Issue by nmadhavi33** [micrometer-metrics/tracing#462]

**Comment by jonatan-ivanov** [comment]
You did not add too much details to this issue so I don't really know what you are trying to do but my guess is:
You need to setup AOP, if you are using Spring Boot before 3.2, you need to create a `SpanAspect` `@Bean`. Starting from 3.2 this should be auto-configured for you but `spring-boot-starter-aop` should be on the classpath.
