### ISSUE TITLE
Testing traces with SpringBoot

### ISSUE THREAD

**Issue by JordiMartinezVicent** [micrometer-metrics/tracing#463]
Recently I had the need of doing some integration tests that include components declared as Beans which generate traces and I had some drawbacks. I would like to share them with you and if you agree, I could contribute to the repo with the solution I found. (Not sure if this is the right repo, as micrometer-tracing does not include Spring Boot. If it is not, I would appreciate your opinion and the redirection to the right repo). 

On one hand, I tried the approach of using the `micrometer-tracing-test` injecting the `SimpleTracer` as a bean, so the spring components make use of it. But I realized that some components are not executed. For example: 

- Compoments used by the vendor implementation like `io.micrometer.tracing.otel.bridge.Slf4JBaggageEventListener ` (otel is the implementation which I am using at the project) or io.opentelemetry.sdk.trace.SpanProcessor.  But also
- Components from the micrometer api like `io.micrometer.tracing.exporter.SpanFilter` that although they are generic, they are called by the implementation bridge. (For example from `io.micrometer.tracing.otel.bridge.CompositeSpanExporter`). 

On the other hand, I tried to use the `micrometer-tracing-integration-test` but I could not publish the Tracer created there as a bean. 

Having said that, I would suggest to have some tracing testing tool which integrates with Spring Boot and can make test like the following: 

```java 

@SpringBootTest(classes = TracingTestWithSBTestConfig.class)
@TracingTest //JunitExtension + Spring Config
@EnableAutoConfiguration
class TracingTestWithSBTest {

  @Autowired
  private InstrumentedComponent instrumentedComponent;

  @Spans
  private SpanCollector spanCollector;

  @Test
  void smoke() {

    this.instrumentedComponent.doSomethingWithTrace();

    TracingAssertions.assertThat(this.spanCollector.getFinishedSpans())
        .hasNumberOfSpansEqualTo(1)
        .hasASpanWithName("instrumented-component-span");

  }

  @Test
  void assertTags() {

    this.instrumentedComponent.doSomethingWithTrace();

    TracingAssertions.assertThat(this.spanCollector.getFinishedSpans())
        .hasNumberOfSpansEqualTo(1)
        .assertThatASpanWithNameEqualTo("instrumented-component-span")
        .hasTag("tag", "tag-value");
  }
}
```

Where the key points would be: 

- The annotation `@TracingTest` would declare the tracing beans to be used by Spring Boot auto-configurations
- The annotation `@TracingTest` would contain a junit extension to manage the tests lifecycle. 
- The user test would not be coupled to any vendor, just to micrometer-tracing api.  The SpanColletor is a generic class to decouple the tests from the vendor classes. 
- The TracingAsserts would be done using the micrometer-api  

I have a naive approach with the opentelemetry vendor. If you feel that it could be useful, I could  share it with you, and if you like it,  contribute to the project.

**Comment by JordiMartinezVicent** [comment]
> I think what you described is very similar to what we have with [@AutoConfigureObservability](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.tracing) except the SpanCollector component that you need to implement as of today (see above the SpanExporter/SpanHandler scenario). I think doing this would be great, could you please open a similar issue to Boot, we can add a test collector component and Boot can auto-configure it if you ask for that 

I have just open a similar issue to the Spring Boot at https://github.com/spring-projects/spring-boot/issues/38796

`(we need to figure out when and how because of the memory leak issue).`

In my approach I have created a JUnit extension to manage it. With which I clear the collected spans. 

I have created a personal repo with it. You can take a look at https://github.com/JordiMartinezVicent/spring-boot-tracing-test/

@jonatan-ivanov

**Comment by jonatan-ivanov** [comment]
@JordiMartinezVicent 
Could you please take a look if `brave.test.TestSpanHandler` (Brave) or [`ArrayListSpanProcessor`](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/ArrayListSpanProcessor.java) (OTel) could help?
Credits belong to @marcingrzejszczak.

**Comment by JordiMartinezVicent** [comment]
> @JordiMartinezVicent Could you please take a look if `brave.test.TestSpanHandler` (Brave) or [`ArrayListSpanProcessor`](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/ArrayListSpanProcessor.java) (OTel) could help? Credits belong to @marcingrzejszczak.

@jonatan-ivanov 

Sure!  We could use the __brave.test.TestSpanHandler__ to extend the tool with brave implementation. 

Besides, in my example I use a [io.opentelemetry.sdk.testing.exporter.InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java) which implements __SpanExporter__, the same as the __ArrayListSpanProcessor__.  I do not see clearly the difference between both... but yes,  the tool could use the most convenient implementation. 

What I would do, would be to not to couple the user's tests to a concrete implementation (brave or otel) but to create a generic interface, like [SpanCollector](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/test/tracing/extension/SpanCollector.java) with which to retrive the spans.

**Comment by jonatan-ivanov** [comment]
@JordiMartinezVicent
>What I would do, would be to not to couple the user's tests to a specific implementation (brave or otel) but to create a generic interface, like [SpanCollector](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/test/tracing/extension/SpanCollector.java) with which to retrive the spans.

This makes sense and I asked the same question yesterday, I think it would be beneficial collecting Micrometer Tracing's spans instead of the underlying implementation's. This would also ease migration.

@marcingrzejszczak Should we deprecate [ArrayListSpanProcessor](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/ArrayListSpanProcessor.java) in favor of [io.opentelemetry.sdk.testing.exporter.InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java)?

**Comment by JordiMartinezVicent** [comment]
> @JordiMartinezVicent
> 
> > What I would do, would be to not to couple the user's tests to a specific implementation (brave or otel) but to create a generic interface, like [SpanCollector](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/test/tracing/extension/SpanCollector.java) with which to retrive the spans.
> 
> This makes sense and I asked the same question yesterday, I think it would be beneficial collecting Micrometer Tracing's spans instead of the underlying implementation's. This would also ease migration.
> 
> @marcingrzejszczak Should we deprecate [ArrayListSpanProcessor](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/ArrayListSpanProcessor.java) in favor of [io.opentelemetry.sdk.testing.exporter.InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java)?

@jonatan-ivanov 

Actually the [io.opentelemetry.sdk.testing.exporter.InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java) is also an otel implementation. What I meant is that I do not know the differences between them. 

In my example, the user's tests uses the interface SpanCollector which is implemented by [OtelInMemoryExporterSpanCollector](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/test/tracing/extension/otel/OtelInMemoryExporterSpanCollector.java) which collect the otel spans and transforms them to __io.micrometer.tracing.exporter.FinishedSpan__ (which are not coupled to the implementation) and can be used with the micrometer TracingAssertions.

**Comment by marcingrzejszczak** [comment]
I didn't know that there is a `[InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java)` . Sure we can deprecate `ArrayListSpanProcessor`.

Created an issue [here](https://github.com/micrometer-metrics/tracing/issues/519).

**Comment by JordiMartinezVicent** [comment]
@jonatan-ivanov 

I have just updated [my example](https://github.com/JordiMartinezVicent/spring-boot-tracing-test) to add the brave implementation. (Note that I could not use the [TestSpanHandler](https://github.com/openzipkin/brave/blob/master/brave/src/test/java/brave/test/TestSpanHandler.java) as it is placed at brave's test source). 

Also I have refactor it to better fit the packages to the following proposal. 

As we were saying, it would need to have some classes at SpringBoot project and others at micrometer's. I would place the micromter classes at `micrometer-tracing-integration-test` because: 

- Even though it does not send the spans to a external component, they use the vendor's code. So they are a kind of integration tests
- This projects already imports the vendor's classes, which are necessary to execute the tests. 

Having said that, I would place the code of my example's package [`org.jordi.tracing.test.test.collector`](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/tree/main/src/main/java/org/jordi/tracing/test/collector) at [`micrometer-tracing-integration-test/io.micrometer.tracing.test.collector`](https://github.com/micrometer-metrics/tracing/tree/main/micrometer-tracing-tests/micrometer-tracing-integration-test/src/main/java/io/micrometer/tracing/test). So this package would have:

- [SpanCollector](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/tracing/test/collector/SpanCollector.java): Generic interface to be implemented by the vendor's 
- [brave/*](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/tree/main/src/main/java/org/jordi/tracing/test/collector/brave): with the implementation of the SpanCollector for brave
- [otel/*](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/tree/main/src/main/java/org/jordi/tracing/test/collector/otel): with the implementation of the SpanCollector for otel

On the other hand, the SpringBoot's would be: 

- [autoconfigure package:](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/tree/main/src/main/java/org/jordi/tracing/autoconfigure) : with the autoconfigurations needed to autowire the tests components for otel and brave 
- [TracingTest](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/tracing/TracingTest.java) Annotation which imports the previous auto-configuration and adds the junit5 extension. 

And finally, we have the junit5 extension [TracingTest](https://github.com/JordiMartinezVicent/spring-boot-tracing-test/blob/main/src/main/java/org/jordi/tracing/extension/TracingExtension.java) which, as @jonatan-ivanov told, to clean-up the spans that you collected. 

I do not know where I would place the extension.. as it needs the spring context to work. What do you think? 


If you agree that it is a worthy tool and (at least) the micrometer's code would be well placed there, I can open a PR with this and start working there.

**Comment by jonatan-ivanov** [comment]
Sorry for the late reply. I think I like the idea of having a generic `SpanCollector` on Micrometer Tracing level, my thoughts:
- We should be careful to implement them in a way that ensures that the majority of the flow is tested. So it should not only test the instrumentation, Micrometer Tracing, and a little part of the tracing library but it should be "deep" enough so that we could verify the spans that would be exported by the tracer. I think your implementation with the `SpanHandler` and the `SpanExporter` should be "deep" enough for this.
- For the API side of the `SpanCollector`, I'm thinking if we should do something similar to `ArrayListSpanProcessor`/your brave implementation fr both OTel and Brave (back the implementation by a queue).
- Also, I'm not sure I get what the `close` method would do. It makes sense for an (OTel) exporter since that usually utilizes a thread pool that you should shut down but seems useless for a component like `SpanCollector`. Also, should we call it `TestSpanCollector` to indicate this is for testing purposes.

Do you want to create such a PR in Micrometer Tracing? Once that is merged, we can add auto-configuration for this in Boot.

@marcingrzejszczak What do you think?

**Comment by marcingrzejszczak** [comment]
I think we should do it like this

- In Brave and OTel packages we need a Queue based implementation of the `SpanReporter` (SR) interface from Micrometer Tracing (similar to this [one](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/ArrayListSpanProcessor.java))
  - We will need another interface for that like `TestSpanReporter` (TSR) that will allow to retrieve spans from queue (`TSR` would extend `SR`)
  - They would automatically get registered in the appropriate composite (examples for [Brave](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/CompositeSpanHandler.java), [OTel](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/CompositeSpanExporter.java), injection points in Boot for [Brave](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/BraveAutoConfiguration.java#L87), [OTel](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/OpenTelemetryAutoConfiguration.java#L121-L128))
- We need an annotation in Spring Boot like `@TracingTest` that would register those reporters as beans and automatically do `@AutoConfigureObservability` with tracing
- With that we would have our `TestSpanReporter` injectable as a bean in the test and we would have access to `FinishedSpan`s

Additional features  that we could consider is to automatically wrap each test method with a span and log out its identifiers. That way the test suite could be pushed to a tracing visualization system too.

**Comment by marcingrzejszczak** [comment]
I've created a PR [here](https://github.com/micrometer-metrics/tracing/pull/574), please tell me what you think.

Of course Spring Boot would require to add the `@TracingTest` annotation that would register the `TestSpanReporter`.

**Comment by marcingrzejszczak** [comment]
I've created an issue in Spring Boot [here](https://github.com/spring-projects/spring-boot/issues/39451)

**Comment by JordiMartinezVicent** [comment]
Also we would need a mechanism to clear that queue between tests. (JUnit extension?)

**Comment by alexanderankin** [comment]
adding a permalink of the examples for future travellers - https://github.com/micrometer-metrics/micrometer-samples/blob/06e8b58ddb49b11fa6802bb080c207adc2a20fc6/micrometer-samples-boot3-web/src/test/java/io/micrometer/boot3/samples/web/Boot3WithWebSampleApplicationTests.java
