### ISSUE TITLE
Spring Boot 3.2.1 misbehave with micrometer-tracing-bridge-brave:1.2.1

### ISSUE THREAD

**Issue by surmabck** [micrometer-metrics/tracing#504]
## The issue
Some MDC data are missing after upgrading Spring Boot to 3.2.1

### Context
After bumping my project to Spring Boot 3.2.1 which introduces the newest micrometer-tracing deps, my tests started to fail because of the lack of some attributes in the MDC. I was able to track the issue down to  micrometer-tracing-bridge-brave:1.2.1. Downgrading this particular dependency to 1.2.0 solves the problem.   (Uncomment `build.gradle.kts:47` in the reproducer to downgrade  micrometer-tracing-bridge-brave to 1.2.0)

### Reproducer
I've created minimal reproducer in here: https://github.com/surmabck/spring-boot-3xx-micrometer-issues/tree/micrometer-1.2.1-springboottests-misbehave

#### Worth to notice
 - Reproducer contains 2 tests. 
   - If you run them separately, they work:
 
![image](https://github.com/micrometer-metrics/tracing/assets/16326758/f519ba0b-0ab4-413f-9cea-5829de85e0cd)
![image](https://github.com/micrometer-metrics/tracing/assets/16326758/8130b5ce-19d0-4360-b7d8-0666e32668a5)
   - if you run them together, they fail:
![image](https://github.com/micrometer-metrics/tracing/assets/16326758/6318c40f-f97c-48bb-903e-e5a3e00bf98e)
- Reproducer contains `ContextEnhancingWebFilter` filter, which does two things:
  - add given string as a baggage via `Tracer` -> `ContextEnhancingWebFilter:40`
  - add given string in in  Reactor's reactive context -> `ContextEnhancingWebFilter: 48`  **Commenting out this line, fixes MDC**
- Reproducer contains two instances of `ContextEnhancingWebFilter` in the Srping Context which adds **different** strings into the context.  See `ContextEnhancingConfiguration`. **Having just one such filter does not reproduce the issue**
- Reproducer tests if given string is being logged correctly (in the MDC context and in the plain, by extracting the string from reactive context)

### Expected behaviour
Running tests together, either via IDE or gradle should work.

**Comment by marcingrzejszczak** [comment]
If you rewrite this to plain Java do you see the same problem? There are so many moving parts here, Kotlin + Reactor + Context Propagation, let's try one thing at a time.

**Comment by marcingrzejszczak** [comment]
cc @sdeleuze in case anything obvious comes to your mind

**Comment by surmabck** [comment]
The reproducer is now rewritten to Java. The issue is still there.

**Comment by sdeleuze** [comment]
> cc @sdeleuze in case anything obvious comes to your mind

Nothing specific, and looks like it also happens in Java, so I will let you have a deeper look.

**Comment by marcingrzejszczak** [comment]
With the quite bug changes from this [PR](https://github.com/micrometer-metrics/tracing/pull/508). The [provided sample](https://github.com/surmabck/spring-boot-3xx-micrometer-issues/compare/micrometer-1.2.1-springboottests-misbehave...marcingrzejszczak:spring-boot-3xx-micrometer-issues:micrometer-1.2.1-springboottests-misbehave?expand=1#diff-1d7ba6836beb2592bae39c9eeac74023dd62d3c8e6790df46303d7418bd68456R30-R32) works well after adding the `ObservationAwareBaggageThreadLocalAccessor`.
