### ISSUE TITLE
Include db.system in the span for a jdbc query

### ISSUE THREAD

**Issue by sunyongh** [micrometer-metrics/tracing#543]
We are using the latest micrometer tracing to instrument the jdbc queries to a postgre sql db in a spring boot application.  We can see the following 2 span  attributes in the generated spans.  Is it possible to include the attribute `db.system` into the span? This way, the backend code can identify it as a database client call for further processing.
```
{
  "peer.service": "dataSource",
  "jdbc.query[0]": "SELECT \"animal\".\"id\" AS \"id\", \"animal\".\"name\" AS \"name\" FROM \"animal\" WHERE \"animal\".\"name\" = ?"
}
```
Btw, `db.system` is a required attribute according to the semantic conventions of Database.  https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/db.md

key information in the pom.xml.
```
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.1</version>
        <relativePath/>
 </parent>
    
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
            <version>1.34.1</version>
        </dependency>
        <dependency>
            <groupId>net.ttddyy.observation</groupId>
            <artifactId>datasource-micrometer-spring-boot</artifactId>
            <version>1.0.3</version>
        </dependency>
```

**Comment by marcingrzejszczak** [comment]
Please create an issue in this repository https://github.com/jdbc-observations/datasource-micrometer

**Comment by liurui-1** [comment]
Hi @marcingrzejszczak ,
We opened an [issue](https://github.com/jdbc-observations/datasource-micrometer/issues/34) in https://github.com/jdbc-observations/datasource-micrometer .
They just closed the issue and said they do not need to support OTel required resource attribute.
So, the `micrometer-tracing-bridge-otel` should support the OTel required Semantic Convention. What do you think?

**Comment by sunyongh** [comment]
@marcingrzejszczak I have opened a similar [issue](https://github.com/jdbc-observations/datasource-micrometer/issues/34#issuecomment-1897670073) for datasource-micrometer.  But they think that `db.system` is just for otel instrumentation, but it is not for non otel instrumentations.  They don't want to add the db specific detection logic and maintain the list of db identifiers. 
Can this request be implemented in the micrometer-tracing-bridge-otel as it targets to the OTel users?  Thanks.

**Comment by marcingrzejszczak** [comment]
Definitely not because in `bridge-otel` we do not have any instrumentation related code. You can modify the default convention and attach the db.system by yourself.
