### ISSUE TITLE
micrometer-tracing-bridge-otel how to create baggage?

### ISSUE THREAD

**Issue by aswarcewicz** [micrometer-metrics/tracing#561]
Hi!

My problem is in creating new baggage when using `micrometer-tracing-bridge-otel` (in brave it's easy).
I have implemented few `OrderedWebFilter` one of them contains principalName and other contains hashedSessionId
Now I would like to place all this data in MDC for logger and pass it to `otel-collector` too, can anybody give me a small example how to achieve it?
@marcingrzejszczak I saw that you are an author of many classes there will you have knowledge how to add baggage in OTEL implementation?

**Comment by marcingrzejszczak** [comment]
Please read the docs https://docs.micrometer.io/tracing/reference/api.html#_micrometer_tracing_baggage_api

**Comment by aswarcewicz** [comment]
I saw it already. Maybe it wasn’t obvious and I forgot to mention that I have been using WebFlux. Docs are fine but not for reactive approach. I try to use Spans makeCurrent method and then close it in doFinally (Mono method) but Span unfortunately leaks and I’ve seen baggages for other requests too. If you have some tips how to use baggages in WebFlux Filters I will be grateful :)

**Comment by marcingrzejszczak** [comment]
I see. There's a problem with baggage in reactor and you can check how things got improved using the [latest snapshots](https://docs.micrometer.io/tracing/reference/1.2-SNAPSHOT/configuring.html#_context_propagation_with_micrometer_tracing).

**Comment by aswarcewicz** [comment]
I have just tried `1.2.3-SNAPSHOT` and either I'm doing something wrong or there is a new bug there (only when I'm using contextWrite with ReactorBaggage).

I have added 

```
public static void main(String[] args) {
        SpringApplication.run(GatewayApp.class, args);
        Hooks.enableAutomaticContextPropagation();
    }
```

and 

```
ObservabilityAutoConfiguration(Tracer tracer, ObservationRegistry registry) {
        ContextRegistry.getInstance().registerThreadLocalAccessor(new ObservationAwareSpanThreadLocalAccessor(tracer));
        ContextRegistry.getInstance().registerThreadLocalAccessor(new ObservationAwareBaggageThreadLocalAccessor(registry, tracer));
    }
```

and in filter I've added

```
return chain.filter(exchange)
                            .contextWrite(ReactorBaggage.append(USER_ID_MDC_FIELD, userId(principal)));
```

And spanId and traceId are broken now, please look at values after gateway word.
`
2024-02-03 21:45:47.050 | [Gateway,00000000000000000000000000000000,0000000000000000] [,] | INFO  | c.e.y.observability.AccessLogging | << Service successfully returns result, statusCode=[200 OK]`


When I deleted `.contextWrite(ReactorBaggage.append(USER_ID_MDC_FIELD, userId(principal)))` everything looks fine and below there are example logs:
`
2024-02-03 21:47:37.599 | [Gateway,caabb6d1418ac32c8308aa6ec456a71e,9c9d22a8bef08223] [,] | INFO  | c.e.y.observability.AccessLogging | << Service successfully returns result, statusCode=[200 OK]`

**Comment by aswarcewicz** [comment]
I will investigate it a little bit more...
I've tried to make minimal app with this bug and I've seen that problem with zeros depends on place where I used `.contextWrite`
