### ISSUE TITLE
Remove unused OTel Logging Exporter dependency

### ISSUE THREAD

**Issue by ciscoo** [micrometer-metrics/tracing#562]
https://github.com/micrometer-metrics/tracing/blob/94d1143ab9b18db09166142733d8e3427952f79d/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/build.gradle#L16C32-L16C62

Per the [README](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md):

> This exporter is being deprecated in favour of the [debug exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md). It will be removed in September 2024.

**Comment by shakuzen** [comment]
Thank you for bringing this to our attention. I'm not sure if that dependency is being used currently. I tried removing it on `main` and the build still passes. @marcingrzejszczak or @jonatan-ivanov do you know?

**Comment by jonatan-ivanov** [comment]
I think we might discuss about two things here:

1. `io.opentelemetry:opentelemetry-exporter-logging` (written in java, part of the OTel Java SDK, [Maven Central](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-exporter-logging), [source](https://github.com/open-telemetry/opentelemetry-java/tree/3e7302e742227d4526b765621a933d748012c906/exporters/logging/src/main/java/io/opentelemetry/exporter/logging))
2. Logging exporter (written in Go, part of the OTel collector, [source](https://github.com/open-telemetry/opentelemetry-java/tree/3e7302e742227d4526b765621a933d748012c906/exporters/logging/src/main/java/io/opentelemetry/exporter/logging))

Deprecating the collector module (`#2`) should have no effect on Micrometer Tracing, I guess @ciscoo meant the dependency (`#1`) but found the wrong deprecation note, the dependency should be stable and not deprecated.

Though that dependency seems unused as @shakuzen found out, I think it was only added for testing/troubleshooting/development purposes (with the first PR) and we forgot to remove.
I think we should remove it. @ciscoo Thank you for bringing this to our attention!
