### ISSUE TITLE
Overwrite autogenerated traceId in Spring WebFlux app with own value set via HTTP Header

### ISSUE THREAD

**Issue by majoferenc** [micrometer-metrics/tracing#564]
**Please describe the feature request.**
Our team needs to push custom traceId into OTLP tracing, which is being generated on frontend side & published in our app via custom HTTP Header. At the moment this is not possible as micrometer generates ImmutableTracingContext.

**Rationale**
Using custom traceId makes possible to control behaviour of tracing from external source & it provides option to trace request from external frontend app across the microservice chain.

**Comment by shakuzen** [comment]
I've transferred the issue to the tracing repository.

> which is being generated on frontend side & published in our app via custom HTTP Header.

Do you want the app that is receiving the trace ID from the frontend to use a well-known propagation format like B3/W3C when it interacts with external services or do you want it to use the custom header or both?

You shouldn't overwrite the traceId but rather you should configure a custom propagation that looks for your custom header and extracts the trace ID from there. Are you using the OTel tracer?

**Comment by majoferenc** [comment]
Thank you.
Yes, that's correct, it would be enough for us to have a custom propagation that looks for custom header and use traceId from it instead of generating it automatically. Of course, if there is not custom header present, autogenerated traceId will be created.
That's correct, we are using OTLP tracing.

**Comment by shakuzen** [comment]
Thanks. What I'm wondering is if Microservice2 etc in the diagram expects the trace ID in the same custom header that the frontend is using or is it expecting it in a standard header as defined in B3/W3C?

**Comment by majoferenc** [comment]
As frontend is connected only to microservice1, it's enough that microservice1 will read customheader, then the next microservice in chain can receive it in a standard way.

**Comment by marcingrzejszczak** [comment]
The preferred option is not to use custom trace id but to just treat the custom trace id as baggage. That means that the `CustomTraceId` header would get propagated over the wire. Would that be acceptable?

**Comment by marcingrzejszczak** [comment]
You can create your own generation either through Brave or OpenTelemetry API. There's nothing that Micrometer Tracing can do here because we simply delegate work to either Brave or OTel. I would highly discourage you do that really.
