### ISSUE TITLE
ObservationAwareSpanThreadLocalAccessorTests$BraveConfig is flaky

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/tracing#625]
See, e.g., https://app.circleci.com/pipelines/github/micrometer-metrics/tracing/1288/workflows/b9afab51-0380-4aa9-b154-9f08a01c6d3b/jobs/6119

**Comment by marcingrzejszczak** [comment]
Should be fixed through https://github.com/micrometer-metrics/tracing/issues/579 . If not we will reopen the issue
