### ISSUE TITLE
Question: Is Spring Boot 2.7.x and Micrometer Tracing supported?

### ISSUE THREAD

**Issue by morrowyn** [micrometer-metrics/tracing#668]
Hi, 

Is Spring Boot 2.7.x and Micrometer Tracing supported? Or do I need to use Spring Cloud Sleuth instead? I couldn't find any references for this, other than that Micrometer was backported. But it wasn't clear to me if this was only the actuator part.

> Micrometer is the metrics collection facility included in Spring Boot 2’s Actuator. It has also been [backported](https://micrometer.io/docs/ref/spring/1.5) to Spring Boot 1.5, 1.4, and 1.3 with the addition of another dependency.

Source: https://spring.io/blog/2018/03/16/micrometer-spring-boot-2-s-new-application-metrics-collector

Regards,

**Comment by shakuzen** [comment]
Auto-configuration support for Micrometer Tracing is not available in Spring Boot 2.7.x.
Spring Cloud Sleuth offers auto-configuration and tracing instrumentation compatible with Spring Boot 2.7.
