### ISSUE TITLE
Publish recent documentation under a fixed version number 

### ISSUE THREAD

**Issue by Seungpang** [micrometer-metrics/tracing#731]
### Description
Currently, Micrometer publishes the latest documentation at https://docs.micrometer.io/tracing/reference, but does not provide a version-specific link for each release. This issue makes it challenging to reference a specific version of the documentation.

For example, linking to version 1.2 can be done via [Micrometer Tracing v1.2](https://docs.micrometer.io/tracing/reference/1.2/), but attempting to link to version 1.3 via [Micrometer Tracing v1.3](https://docs.micrometer.io/tracing/reference/1.3/) results in a 404 error.

### Rationale
Having version-specific documentation links is crucial for referencing and ensuring users access the correct version of the documentation.

### Additional Context
This issue is similar to the one raised for Micrometer's main documentation in [spring-projects/spring-boot#40916](https://github.com/spring-projects/spring-boot/issues/40916).

**Comment by jonatan-ivanov** [comment]
Should be fixed, see: https://github.com/micrometer-metrics/micrometer/issues/5152#issuecomment-2183164231

All these should work:
- https://docs.micrometer.io/tracing/reference/1.3/index.html
- https://docs.micrometer.io/tracing/reference/1.3/configuring.html
- https://docs.micrometer.io/tracing/reference/1.3/configuring.html#_exemplars
- https://docs.micrometer.io/tracing/reference/1.3/
- https://docs.micrometer.io/tracing/reference/1.3
