### ISSUE TITLE
`@Nullable` annotation is missing from methods that may return null

### ISSUE THREAD

**Issue by m15o** [micrometer-metrics/tracing#732]
We have kotlin test codes using BraveTracer, but we get inaccurate warnings from the kotlin compiler.

For example, following code is warnde by the compiler with `Unnecessary safe call on a non-null receiver of type Span` message:
```kotlin
internal class TracerTest {
    @Test
    fun test() {
        val tracing = brave.Tracing.newBuilder().build()
        val tracer = BraveTracer(tracing.tracer(), BraveCurrentTraceContext(tracing.currentTraceContext()))
        assertThat(tracer.currentSpan()?.context()?.traceId()).isNull()
    }
}
```

This is because [`io.micrometer.tracing.brave.bridge` package have `@NonNullApi`](https://github.com/micrometer-metrics/tracing/blob/v1.3.0/micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/package-info.java#L17-L19), but [`BraveTracer.currentSpan()` do not have `@Nullable` annotation](https://github.com/micrometer-metrics/tracing/blob/v1.3.0/micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/BraveTracer.java#L83-L90).
We are not sure, but other methods might also missing `@Nullable` annotation.

**Comment by marcingrzejszczak** [comment]
Yikes! Are you willing to file a PR to help us out?

**Comment by ttddyy** [comment]
But shouldn't it inherit `@Nullable` from the interface even though they are in different packages?
I see [`Tracer.currentSpan()`](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing/src/main/java/io/micrometer/tracing/Tracer.java#L237-L238) interface is annotated with `@Nullable`.

**Comment by m15o** [comment]
By type castting `BraveTracer` to `Tracer`, the warning goes away.
I think `BraveTracer` has narrower type, so if you use `BarveTracer` itself, the `BraveTracer.currnet()` is treated as not-null.

**Comment by m15o** [comment]
> Yikes! Are you willing to file a PR to help us out?

And, yes, I'd like to contribute.

**Comment by ttddyy** [comment]
Looking at Spring Framework, the implementation class also declares `@Nullable` if the method could return `null`.
For example, [RestOperation](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/client/RestOperations.java#L55-L56) interface against [RestTemplate](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java#L408-L409) implementation class.

So, I think it would be a good PR for @m15o to fix this.
