### ISSUE TITLE
Question: Hot to set the service name in otel tracing?

### ISSUE THREAD

**Issue by mmaier2** [micrometer-metrics/tracing#759]
Hi,

On a spring boot 3.3.x application with micrometer-tracing-bridge-otel(1.3.1) and opentelemetry-exporter-otlp(1.37.0) and so far entirely relying on autoconfiguration.
I would like to set the service name. The default is to use the spring boot's application name. Is there some property or other way to override this behavior? 

Thanks a lot
Markus

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/opentelemetry/OpenTelemetryAutoConfiguration.java#L73 you can create your own resource that should override the default one
