### ISSUE TITLE
Help for configuration of sending traces

### ISSUE THREAD

**Issue by fernandoscruz** [micrometer-metrics/tracing#769]
Help for configuration of sending two traces

Please help me find the variable documentation to configure or send the trace?

**Comment by fernandoscruz** [comment]
I used the opentelemetry doc as a reference, but it doesn't work

https://opentelemetry.io/docs/languages/java/configuration/

**Comment by jonatan-ivanov** [comment]
It's not clear what you are trying to do, you can find the docs here: https://micrometer.io/
