### ISSUE TITLE
TraceId for empty header request

### ISSUE THREAD

**Issue by Renboo** [micrometer-metrics/tracing#844]
Hello!

I use your library with spring and it works greate for my tasks. But today i have a requirement to generate TraceId and spanId for requests that does not send that data to my service.
Is any simplest way do do that? May be property for spring properties? Or i should create prefilter for you web filter?

Just for info: reactive kafka library uses that logic from out of the box. I mean starting new trace Id for messages that has no TraceId.

**Comment by marcingrzejszczak** [comment]
Any Spring Boot application will do this out of the box through a Servlet filter or a Reactive WebFilter. Creation of a new trace id for any incoming request that has no trace id in the headers is a basic feature.
