### ISSUE TITLE
@NewSpan does not take into account ObservationPredicate

### ISSUE THREAD

**Issue by mfvanek** [micrometer-metrics/tracing#863]
Hello there!

I'd like to disable tracing during warming-up of application.

I started with a custom `SpanExportingPredicate`, but due to the asynchronous nature of exporting, some batches of spans were still sent to the OTLP-collector (even after the warm-up was completed).

Then I tried to implement a custom `ObservationPredicate`. This almost solved my issue, but I ran into a problem with the `@NewSpan` annotation. The traces generated by `@NewSpan` seems to ignore the registered observation predicates.
Is this by design?
How can I reliably disable/filter out such spans?

Thanks in advance.

**Comment by mfvanek** [comment]
A little code to illustrate the main idea:
```kotlin
@Configuration(proxyBeanMethods = false)
@ConditionalOnClass(name = ["io.micrometer.tracing.Tracer", "io.micrometer.observation.ObservationPredicate", "io.micrometer.tracing.exporter.SpanExportingPredicate"])
open class TracingWarmupAutoConfiguration {

    @Bean
    @ConditionalOnMissingBean(name = ["traceExportActivitySwitchHook"])
    open fun traceExportActivitySwitchHook(): WarmingUpHook =
        TracesExportActivitySwitchHook(traceExportDisabledState) // manages state of traceExportDisabledState

    @Bean
    @ConditionalOnMissingBean(name = ["tracingDisabledDuringWarmupObservationPredicate"])
    open fun tracingDisabledDuringWarmupObservationPredicate(): ObservationPredicate =
        ObservationPredicate { _, _ -> !traceExportDisabledState.get() }

    @Bean
    @ConditionalOnMissingBean(name = ["spanExportingDisabledDuringWarmupPredicate"])
    open fun spanExportingDisabledDuringWarmupPredicate(): SpanExportingPredicate =
        SpanExportingPredicate { _ -> !traceExportDisabledState.get() }

    companion object {
        @JvmStatic
        private val traceExportDisabledState: AtomicBoolean = AtomicBoolean()
    }
}
```

**Comment by marcingrzejszczak** [comment]
> Then I tried to implement a custom ObservationPredicate. This almost solved my issue, but I ran into a problem with the @NewSpan annotation. The traces generated by @NewSpan seems to ignore the registered observation predicates.

ObservationPredicates work with observations. If you want to filter out all spans for tests or sth like that just set the tracing sampling probability to 0. Then not a single span will be sent out.

**Comment by mfvanek** [comment]
> ObservationPredicates work with observations.

From my perspective, micrometer-tracing uses micrometer-observation.
As far as I understand, trace is a kind of observation, isn't it?
So why not to handle observation predicates while creating a span in [ImperativeMethodInvocationProcessor](https://github.com/micrometer-metrics/tracing/blob/65e2c9e4c44a1541ccbd2671702e3923a5ea9442/micrometer-tracing/src/main/java/io/micrometer/tracing/annotation/ImperativeMethodInvocationProcessor.java#L76)?

With Spring Boot 2 and Sleuth I used `Tracer` instance:
```kotlin
    fun getQuoteUsingTracer(): String {
        val newSpan: Span = tracer.nextSpan().name("getQuote")
        try {
            tracer.withSpan(newSpan.start()).use {
                //delay(FIXED_DELAY_MS)
                return quotes.random()
            }
        } catch (e: Exception) {
            newSpan.error(e)
            throw e
        } finally {
            newSpan.end()
        }
    }
```

I was able to rewrite it with `Observation`:
```kotlin
    fun getQuoteUsingObservation(): String {
        val observation = Observation.createNotStarted("getQuote", observationRegistry).start()
        try {
            //delay(FIXED_DELAY_MS)
            return quotes.random()
        } catch (e: Exception) {
            observation.error(e)
            throw e
        } finally {
            observation.stop()
        }
    }
```
Now it works as I expected: takes into account observation predicates and doesn't produce spans in my case.

But I don't have a replacement for `@NewSpan` with the same behavior:
```kotlin
    @NewSpan("getQuoteAsMono")
    fun getQuoteAsMono(parentTraceId: String, parentSpanId: String): Mono<String> {
        return Mono.fromCallable { quotes.random() }
            .delayElement(Duration.ofMillis(FIXED_DELAY_MS))
    }
```
~~May be we need something like `@NewObservation`?~~
Oh, I wrote it and realized that there is `@Observed`! I'll try it.

> If you want to filter out all spans for tests or sth like that just set the tracing sampling probability to 0. Then not a single span will be sent out.

I need it at runtime. I have not yet found an easy way to change sampling probability at runtime.

**Comment by marcingrzejszczak** [comment]
Instead of `@NewSpan` just use `@Observed` and then your predicate will work.

> I need it at runtime. I have not yet found an easy way to change sampling probability at runtime.

Use spring cloud, change the property and [refresh](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#refresh-scope) it at runtime?

**Comment by jonatan-ivanov** [comment]
I think Marcin's answers are already providing a solution for your issue but for the sake of completeness, let me add some details.

I guess this is where the misunderstanding is coming from:
>From my perspective, micrometer-tracing uses micrometer-observation.

The reality is that the Observation API can call micrometer-tracing if a tracing handler is registered, not the other way around.

>As far as I understand, trace is a kind of observation, isn't it?

No, a span is an output that can be created by a handler in response of observations are created. (A trace is a set of spans.)

>So why not to handle observation predicates while creating a span in [ImperativeMethodInvocationProcessor](https://github.com/micrometer-metrics/tracing/blob/65e2c9e4c44a1541ccbd2671702e3923a5ea9442/micrometer-tracing/src/main/java/io/micrometer/tracing/annotation/ImperativeMethodInvocationProcessor.java#L76)?

Because it has nothing to do with Observations, see above.

Please check the docs: https://docs.micrometer.io/micrometer/reference/observation/introduction.html

The gist of it: `ObservationHandler`s are listeners that can react to events when somebody starts/stops an `Observation`, signals an error, etc. These reactions can be starting and stopping a timer and record metrics, emit log events, or create and stop spans. When spans are created through an `Observation`, the `ObservationPredicate` can make that `Observation` "ignored" so no span will be created. But if you just create a span on your own or you use `@NewSpan`, the Observation API has no idea about it since `Span` is a lower-level concept than an `Observation`.

Does this make sense?

**Comment by mfvanek** [comment]
@jonatan-ivanov @marcingrzejszczak 
Thank you very much
