### ISSUE TITLE
OTel Span is not set to status "ok" when ends successfully

### ISSUE THREAD

**Issue by GFriedrich** [micrometer-metrics/tracing#890]
Hi,
I'm not sure if I'm missing something in my implementation, but I would expect that if an OTel span is ended and is yet "unset", it would be set to "ok".
Right now I can see it is always "unset" at the end which is somewhat odd.
But please let me know in case I've missed anything.
Thanks for looking at it in advance.

**Comment by jonatan-ivanov** [comment]
Thanks for the issue!
Are you interested in creating a PR to fix this?
[`OtelSpan`](https://github.com/micrometer-metrics/tracing/blob/9143d7ac6448aa125f3153bedf99e4bba2f82651/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelSpan.java) has two `end` methods and the `error` method is already setting the status so setting in `end` should be straightforward.

**Comment by GFriedrich** [comment]
@jonatan-ivanov first of all: Thanks for checking.
Sure, I can create a PR with a fix, but it may take until the weekend.

**Comment by jonatan-ivanov** [comment]
That's totally fine, our next release is in two weeks. I asked since this seems a good issue if one wants to contribute. If you don't or you won't find the time, that's of course 120% fine, just let me know and I fix it.

**Comment by jonatan-ivanov** [comment]
>some of the builder methods are returning a copy of the OtelSpan for no good reason

Let's do this in a separate PR.

**Comment by GFriedrich** [comment]
> > some of the builder methods are returning a copy of the OtelSpan for no good reason
> 
> Let's do this in a separate PR.

Have created a separate issue (#900) and PR (#901) for it.
Thanks @jonatan-ivanov 🤝
