### ISSUE TITLE
How can i use Nginx generate TraceId(x-b3-trace) to relace micrometer traceid?

### ISSUE THREAD

**Issue by QDoubleM** [micrometer-metrics/tracing#914]
How can i use Nginx generate TraceId(x-b3-trace) to relace micrometer traceid?

**Comment by jonatan-ivanov** [comment]
You did not provide many details but if Micrometer Tracing is configured properly, it will understand and use the B3 propagation format provided by other components (e.g.: if you use Spring Boot, this is supported out of the box).
